/*
 * File: app/view/winCars.js
 *
 * This file was generated by Sencha Architect version 3.5.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('catCar.view.winCars', {
    extend: 'Ext.window.Window',
    alias: 'widget.winCars',

    requires: [
        'catCar.view.winCarsViewModel',
        'Ext.form.Panel',
        'Ext.form.FieldSet',
        'Ext.form.field.ComboBox',
        'Ext.form.field.Date',
        'Ext.form.field.Checkbox',
        'Ext.toolbar.Toolbar',
        'Ext.button.Button',
        'Ext.toolbar.Fill'
    ],

    viewModel: {
        type: 'wincars'
    },
    height: 200,
    id: 'winCars',
    itemId: 'winCars',
    maxHeight: 200,
    minHeight: 200,
    minWidth: 850,
    ui: 'green-window',
    width: 850,
    layout: 'column',
    closable: false,
    title: 'Cars',
    modal: true,

    items: [
        {
            xtype: 'form',
            confirmRecord: function () {
                if (Ext.getCmp('formCars').isValid()) {
                    var formRecord = 'formCars';
                    var apiController = 'apiCars';
                    var apiMethod = 'createCars';

                    var objJsonRequest = new Object();
                    objJsonRequest.apiController = apiController;
                    objJsonRequest.apiMethod = apiMethod;
                    objJsonRequest.apiData = trex.prepareFormFields(formRecord);

                    var functionSuccess = function () {
                        var jsonData = trex.getInfoDataBridge(apiController);

                        trex.showInfo(jsonData, 'information');

                        var winCars = Ext.getCmp('winCars');
                        winCars.close();

                        Ext.getStore('storeCars').load();

                    };

                    var functionFailure = function () {
                        var jsonData = trex.getInfoDataBridge(apiController);
                        trex.showInfo(jsonData, 'error', 'tfCompany');
                    };

                    trex.doDataBridge(objJsonRequest,
                        functionSuccess,
                        null,
                        functionFailure,
                        null);

                }
                else {

                    trex.message('error',
                        'Incomplete Form',
                        'You must fill the required fields');
                }
            },
            columnWidth: 1,
            height: 141,
            id: 'formCars',
            itemId: 'formCars',
            width: 838,
            layout: 'column',
            bodyPadding: 10,
            items: [
                {
                    xtype: 'fieldset',
                    columnWidth: 1,
                    height: 117,
                    id: 'fieldsetCarsInformation',
                    itemId: 'fieldsetCarsInformation',
                    width: 816,
                    layout: 'column',
                    title: '<b>General information</b>',
                    items: [
                        {
                            xtype: 'textfield',
                            columnWidth: 0.25,
                            disabledCls: 'disabledField',
                            id: 'tfCarID',
                            itemId: 'tfCarID',
                            margin: '0 5 5 5',
                            width: 387,
                            fieldLabel: 'Car ID',
                            labelClsExtra: 'requiredField',
                            labelWidth: 70,
                            allowBlank: false
                        },
                        {
                            xtype: 'textfield',
                            columnWidth: 0.75,
                            disabledCls: 'disabledField',
                            id: 'tfCarDescription',
                            itemId: 'tfCarDescription',
                            margin: '0 5 5 5',
                            width: 387,
                            fieldLabel: 'Car Description',
                            labelClsExtra: 'requiredField',
                            labelWidth: 120,
                            allowBlank: false
                        },
                        {
                            xtype: 'combobox',
                            columnWidth: 0.25,
                            disabledCls: 'disabledField',
                            id: 'cbMaker',
                            itemId: 'cbMaker',
                            margin: '0 5 5 5',
                            fieldLabel: 'Maker',
                            labelClsExtra: 'requiredField',
                            labelWidth: 70,
                            allowBlank: false
                        },
                        {
                            xtype: 'combobox',
                            columnWidth: 0.25,
                            disabledCls: 'disabledField',
                            id: 'cbType',
                            itemId: 'cbType',
                            margin: '0 5 5 5',
                            fieldLabel: 'Type',
                            labelClsExtra: 'requiredField',
                            labelWidth: 50,
                            allowBlank: false
                        },
                        {
                            xtype: 'combobox',
                            columnWidth: 0.25,
                            disabledCls: 'disabledField',
                            id: 'cbModel',
                            itemId: 'cbModel',
                            margin: '0 5 5 5',
                            fieldLabel: 'Model',
                            labelClsExtra: 'requiredField',
                            labelWidth: 60,
                            allowBlank: false
                        },
                        {
                            xtype: 'combobox',
                            columnWidth: 0.25,
                            disabledCls: 'disabledField',
                            id: 'cbCly',
                            itemId: 'cbCly',
                            margin: '0 5 5 5',
                            fieldLabel: 'Cyl',
                            labelClsExtra: 'requiredField',
                            labelWidth: 40,
                            allowBlank: false
                        },
                        {
                            xtype: 'datefield',
                            columnWidth: 0.25,
                            disabledCls: 'disabledField',
                            id: 'dtCreatedAt',
                            itemId: 'dtCreatedAt',
                            margin: '0 5 5 5',
                            fieldLabel: 'Created',
                            labelClsExtra: 'requiredField',
                            labelWidth: 70,
                            allowBlank: false
                        },
                        {
                            xtype: 'checkboxfield',
                            columnWidth: 0.17,
                            disabledCls: 'disabledField',
                            id: 'chActive',
                            itemId: 'chActive',
                            margin: '0 5 5 5',
                            labelClsExtra: 'requiredField',
                            boxLabel: 'Active'
                        }
                    ]
                }
            ]
        }
    ],
    dockedItems: [
        {
            xtype: 'toolbar',
            dock: 'top',
            id: 'toolbarCars',
            itemId: 'toolbarCars',
            items: [
                {
                    xtype: 'button',
                    handler: function (button, e) {
                        Ext.getCmp('formCars').confirmRecord();
                    },
                    id: 'btnConfirmCars',
                    itemId: 'btnConfirmCars',
                    width: 120,
                    iconCls: 'ion-checkmark-circled icon16',
                    text: 'Confirm',
                    textAlign: 'left'
                },
                {
                    xtype: 'tbfill',
                    id: 'filCars',
                    itemId: 'filCars'
                },
                {
                    xtype: 'button',
                    handler: function (button, e) {
                        var winCars = Ext.getCmp('winCars');
                        winCars.close();
                    },
                    id: 'btnCloseCars',
                    itemId: 'btnCloseCars',
                    width: 120,
                    iconCls: 'ion-close-circled icon16',
                    text: 'Close',
                    textAlign: 'left'
                }
            ]
        }
    ]

});