/*
 * File: app/view/formMaintenance.js
 *
 * This file was generated by Sencha Architect version 3.5.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('proPayControl.view.formMaintenance', {
    extend: 'Ext.form.Panel',
    alias: 'widget.formMaintenance',

    requires: [
        'proPayControl.view.formMaintenanceViewModel',
        'Ext.button.Button',
        'Ext.toolbar.Separator',
        'Ext.toolbar.Fill',
        'Ext.grid.Panel',
        'Ext.view.Table',
        'Ext.grid.column.Column',
        'Ext.toolbar.Paging'
    ],

    viewModel: {
        type: 'formmaintenance'
    },
    id: 'formMaintenance',
    itemId: 'formMaintenance',
    ui: 'green-panel',
    layout: 'column',
    bodyPadding: 10,
    manageHeight: false,
    defaultListenerScope: true,

    dockedItems: [
        {
            xtype: 'toolbar',
            dock: 'top',
            id: 'toolbarMaintenance',
            itemId: 'toolbarMaintenance',
            items: [
                {
                    xtype: 'button',
                    handler: function (button, e) {
                        Ext.getCmp('formMaintenance').showPayControl();
                    },
                    id: 'btnView',
                    itemId: 'btnView',
                    width: 120,
                    iconCls: 'ion-eye icon16',
                    text: 'View',
                    textAlign: 'left'
                },
                {
                    xtype: 'button',
                    disabled: true,
                    id: 'btnCreate',
                    itemId: 'btnCreate',
                    width: 120,
                    iconCls: 'ion-plus-circled icon16',
                    text: 'Create',
                    textAlign: 'left'
                },
                {
                    xtype: 'button',
                    handler: function (button, e) {
                        var msgFunction = function () {
                            Ext.getCmp('formMaintenance').deletePayControl();

                        };

                        var msgType = 'question';
                        var msgTitle = 'Delete Pay Control';
                        var msgContent = 'Do you want to delete the Pay Control record: ';

                        trex.message(msgType,
                            msgTitle,
                            msgContent,
                            msgFunction);

                        return;
                    },
                    id: 'btnDelete',
                    itemId: 'btnDelete',
                    width: 120,
                    iconCls: 'ion-trash-a icon16',
                    text: 'Delete',
                    textAlign: 'left'
                },
                {
                    xtype: 'tbseparator',
                    width: 30
                },
                {
                    xtype: 'button',
                    id: 'btnFind',
                    itemId: 'btnFind',
                    width: 120,
                    iconCls: 'ion-ios-search-strong icon16',
                    text: 'Find',
                    textAlign: 'left'
                },
                {
                    xtype: 'button',
                    id: 'btnFilter',
                    itemId: 'btnFilter',
                    width: 120,
                    iconCls: 'ion-funnel icon16',
                    text: 'Filter',
                    textAlign: 'left'
                },
                {
                    xtype: 'tbseparator',
                    width: 30
                },
                {
                    xtype: 'tbfill'
                },
                {
                    xtype: 'button',
                    handler: function (button, e) {
                        var winPayControl = Ext.getCmp('winPayControl');

                        if (!winPayControl) {
                            winPayControl = Ext.create('widget.winPayControl');
                            winPayControl.show();
                            trex.hideScrollBars();
                        }
                    },
                    id: 'btnPayments',
                    itemId: 'btnPayments',
                    width: 120,
                    iconCls: 'ion-plus-circled icon16',
                    text: 'Pay Control',
                    textAlign: 'left'
                },
                {
                    xtype: 'button',
                    id: 'btnInformation',
                    itemId: 'btnInformation',
                    width: 120,
                    iconCls: 'ion-information-circled icon16',
                    text: 'Information',
                    textAlign: 'left'
                },
                {
                    xtype: 'button',
                    handler: function (button, e) {
                        var win = window.parent.Ext.getCmp('proPayControl');
                        if (win)win[win.closeAction]();
                    },
                    id: 'btnExit',
                    itemId: 'btnExit',
                    width: 120,
                    iconCls: 'ion-android-exit icon16',
                    text: 'Exit',
                    textAlign: 'left'
                }
            ]
        }
    ],
    items: [
        {
            xtype: 'gridpanel',
            columnWidth: 1,
            id: 'gridPayControl',
            itemId: 'gridPayControl',
            margin: '5 5 5 0',
            maxHeight: 250,
            ui: 'green-panel',
            title: 'Pay Control',
            columnLines: false,
            forceFit: false,
            store: 'storePayControl',
            viewConfig: {
                height: 400,
                width: 300
            },
            columns: [
                {
                    xtype: 'gridcolumn',
                    id: 'pay_document',
                    itemId: 'pay_document',
                    maxWidth: 80,
                    dataIndex: 'pay_document',
                    text: 'Document </br> Number'
                },
                {
                    xtype: 'gridcolumn',
                    id: 'pay_note',
                    itemId: 'pay_note',
                    maxWidth: 250,
                    width: 250,
                    dataIndex: 'inv_total',
                    text: 'Payments </br> Note'
                },
                {
                    xtype: 'gridcolumn',
                    id: 'pay_date',
                    itemId: 'pay_date',
                    dataIndex: 'pay_date',
                    text: 'Payments </br> Date'
                },
                {
                    xtype: 'gridcolumn',
                    id: 'pay_period',
                    itemId: 'pay_period',
                    dataIndex: 'pay_period',
                    text: 'Period'
                },
                {
                    xtype: 'gridcolumn',
                    id: 'pay_amount',
                    itemId: 'pay_amount',
                    dataIndex: 'pay_amount',
                    text: 'Amount'
                },
                {
                    xtype: 'gridcolumn',
                    id: 'pay_tax',
                    itemId: 'pay_tax',
                    dataIndex: 'pay_tax',
                    text: 'Tax'
                },
                {
                    xtype: 'gridcolumn',
                    id: 'pay_total',
                    itemId: 'total',
                    dataIndex: 'pay_total',
                    text: 'Total'
                },
                {
                    xtype: 'gridcolumn',
                    id: 'invoice',
                    itemId: 'invoice',
                    dataIndex: 'invoice',
                    text: 'Invoice'
                },
                {
                    xtype: 'gridcolumn',
                    id: 'invoice_date',
                    itemId: 'invoice_date',
                    dataIndex: 'invoice_date',
                    text: 'Invoice </br> Date'
                },
                {
                    xtype: 'gridcolumn',
                    id: 'invoice_amount',
                    itemId: 'invoice_amount',
                    dataIndex: 'inv_amount',
                    text: 'Invoice </br> Amount'
                },
                {
                    xtype: 'gridcolumn',
                    id: 'invoice_tax',
                    itemId: 'invoice_tax',
                    dataIndex: 'inv_tax',
                    text: 'Invoice </br> Tax'
                },
                {
                    xtype: 'gridcolumn',
                    id: 'invoice_total',
                    itemId: 'invoice_total',
                    dataIndex: 'inv_total',
                    text: 'Invoice </br> Total'
                }
            ],
            dockedItems: [
                {
                    xtype: 'pagingtoolbar',
                    dock: 'bottom',
                    id: 'pagingToolbar3',
                    itemId: 'pagingToolbar2',
                    width: 260,
                    displayInfo: true
                }
            ],
            listeners: {
                itemdblclick: 'onGridPayControlItemDblClick',
                itemclick: 'onGridPayControlItemClick'
            }
        },
        {
            xtype: 'gridpanel',
            columnWidth: 1,
            id: 'gridSerDetail',
            itemId: 'gridSerDetail',
            margin: '5 5 5 0',
            maxHeight: 290,
            ui: 'green-panel',
            title: 'Detail Service',
            columnLines: false,
            forceFit: false,
            store: 'storeSerDetail',
            viewConfig: {
                height: 400,
                width: 300
            },
            columns: [
                {
                    xtype: 'gridcolumn',
                    id: 'num_service',
                    itemId: 'num_service',
                    maxWidth: 80,
                    dataIndex: 'num_service',
                    text: 'Service'
                },
                {
                    xtype: 'gridcolumn',
                    id: 'service_date',
                    itemId: 'service_date',
                    dataIndex: 'service_date',
                    text: 'Savice </br> Date'
                },
                {
                    xtype: 'gridcolumn',
                    id: 'period',
                    itemId: 'period',
                    maxWidth: 80,
                    width: 80,
                    dataIndex: 'period',
                    text: 'Period'
                },
                {
                    xtype: 'gridcolumn',
                    id: 'customer_id',
                    itemId: 'customer_id',
                    dataIndex: 'customer_id',
                    text: 'Customer'
                },
                {
                    xtype: 'gridcolumn',
                    id: 'branch_office',
                    itemId: 'branch_office',
                    dataIndex: 'branch_office',
                    text: 'Branch </br> Office'
                },
                {
                    xtype: 'gridcolumn',
                    id: 'authorizer',
                    itemId: 'authorizer',
                    dataIndex: 'authorizer',
                    text: 'Authorizer'
                },
                {
                    xtype: 'gridcolumn',
                    id: 'sector',
                    itemId: 'sector',
                    dataIndex: 'sector',
                    text: 'Sector'
                },
                {
                    xtype: 'gridcolumn',
                    id: 'zone_end',
                    itemId: 'zone_end',
                    dataIndex: 'zone_end',
                    text: 'Zone'
                },
                {
                    xtype: 'gridcolumn',
                    id: 'appointment',
                    itemId: 'appointment',
                    dataIndex: 'appointment',
                    text: 'Appointment'
                },
                {
                    xtype: 'gridcolumn',
                    id: 'appointment_date2',
                    itemId: 'appointment_date_2',
                    dataIndex: 'appointment_date',
                    text: 'Appointment </br> Date'
                },
                {
                    xtype: 'gridcolumn',
                    id: 'range',
                    itemId: 'range',
                    dataIndex: 'range',
                    text: 'Range'
                },
                {
                    xtype: 'gridcolumn',
                    id: 'time',
                    itemId: 'time',
                    dataIndex: 'time',
                    text: 'Time'
                },
                {
                    xtype: 'gridcolumn',
                    id: 'time_wait',
                    itemId: 'time_wait',
                    dataIndex: 'time_wait',
                    text: 'Time </br> Wait'
                },
                {
                    xtype: 'gridcolumn',
                    id: 'add_costs',
                    itemId: 'add_costs',
                    dataIndex: 'add_cost',
                    text: 'Add </br> Costs'
                },
                {
                    xtype: 'gridcolumn',
                    id: 'taxt',
                    itemId: 'taxt',
                    dataIndex: 'taxt',
                    text: 'Taxt'
                },
                {
                    xtype: 'gridcolumn',
                    id: 'cost',
                    itemId: 'cost',
                    dataIndex: 'cost',
                    text: 'Cost'
                },
                {
                    xtype: 'gridcolumn',
                    id: 'status2',
                    itemId: 'status2',
                    dataIndex: 'total',
                    text: 'Status'
                }
            ],
            dockedItems: [
                {
                    xtype: 'pagingtoolbar',
                    dock: 'bottom',
                    id: 'pagingToolbar2',
                    itemId: 'pagingToolbar2',
                    width: 260,
                    displayInfo: true
                }
            ],
            listeners: {
                itemdblclick: 'onGridSerDetailItemDblClick',
                itemclick: 'onGridSerDetailItemClick'
            }
        }
    ],

    onGridPayControlItemDblClick: function (dataview, record, item, index, e, eOpts) {
        Ext.getCmp('formMaintenance').showSerDetail();
    },

    onGridPayControlItemClick: function (dataview, record, item, index, e, eOpts) {
        Ext.getCmp('formMaintenance').PayControlID = record.data.id;
        Ext.getCmp('formMaintenance').PayControlRecord = record.data;
    },

    onGridSerDetailItemDblClick: function (dataview, record, item, index, e, eOpts) {
        Ext.getCmp('formMaintenance').showSerDetail();
    },

    onGridSerDetailItemClick: function (dataview, record, item, index, e, eOpts) {
        Ext.getCmp('formMaintenance').SerDetailID = record.data.id;
        Ext.getCmp('formMaintenance').SerDetailRecord = record.data;
    },

    showPayControl: function (pMode) {
        var apiController = 'apiPayControl';
        var apiMethod = 'showSerDetail';
        var objJsonData = new Object();
        objJsonData.PayControlID = Ext.getCmp('formMaintenance').PayControlID;

        var objJsonRequest = new Object();
        objJsonRequest.apiController = apiController;
        objJsonRequest.apiMethod = apiMethod;
        objJsonRequest.apiData = JSON.stringify(objJsonData);

        var functionSuccess = function () {
            var jsonData = trex.getInfoDataBridge(apiController);


            var winPayControl = Ext.getCmp('winPayControl');

            if (!winPayControl) {
                winPayControl = Ext.create('widget.winPayControl');
                winPayControl.show();
                trex.hideScrollBars();
            }

            trex.showRecord(jsonData, 'paycontrol');

        };

        var functionFailure = function () {
            var jsonData = trex.getInfoDataBridge(apiController);
        };

        trex.doDataBridge(objJsonRequest,
            functionSuccess,
            null,
            functionFailure,
            null);


    },

    deletePayControl: function () {
        alert('registro borrado');

        var formRecord = 'formPayControl';
        var apiController = 'apiPayControl';
        var apiMethod = 'deletePayControl';

        var objJsonData = new Object();
        objJsonData.PayControlId = Ext.getCmp('formMaintenance').PayControlRecord.id;

        var objJsonRequest = new Object();
        objJsonRequest.apiController = apiController;
        objJsonRequest.apiMethod = apiMethod;
        objJsonRequest.apiData = JSON.stringify(objJsonData);

        var functionSuccess = function () {
            var jsonData = trex.getInfoDataBridge(apiController);

            console.log(jsonData);
            trex.showInfo(jsonData, 'info');

        };

        var functionFailure = function () {
            var jsonData = trex.getInfoDataBridge(apiController);
            trex.showInfo(jsonData, 'error', 'tfCompany');
        };

        trex.doDataBridge(objJsonRequest,
            functionSuccess,
            null,
            functionFailure,
            null);
    }

});