/*
 * File: app/view/winPayControl.js
 *
 * This file was generated by Sencha Architect version 3.5.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('proPayControl.view.winPayControl', {
    extend: 'Ext.window.Window',
    alias: 'widget.winPayControl',

    requires: [
        'proPayControl.view.winExpensesViewModel1',
        'Ext.form.Panel',
        'Ext.form.FieldSet',
        'Ext.form.field.Date',
        'Ext.form.field.TextArea',
        'Ext.toolbar.Toolbar',
        'Ext.button.Button',
        'Ext.toolbar.Fill'
    ],

    viewModel: {
        type: 'winpaycontrol'
    },
    height: 267,
    id: 'winPayControl',
    itemId: 'winPayControl',
    maxHeight: 350,
    minHeight: 250,
    minWidth: 850,
    ui: 'green-window',
    width: 850,
    layout: 'column',
    closable: false,
    title: 'Pay Control',
    modal: true,

    items: [
        {
            xtype: 'form',
            confirmRecord: function () {
                if (Ext.getCmp('formPay').isValid()) {
                    var formRecord = 'formPayControl';
                    var apiController = 'apiPayControl';
                    var apiMethod = 'createPayControl';

                    var objJsonRequest = new Object();
                    objJsonRequest.apiController = apiController;
                    objJsonRequest.apiMethod = apiMethod;
                    objJsonRequest.apiData = trex.prepareFormFields(formRecord);

                    var functionSuccess = function () {
                        var jsonData = trex.getInfoDataBridge(apiController);

                        trex.showInfo(jsonData, 'information');

                        var winPayControl = Ext.getCmp('winPayControl');
                        winPayControl.close();

                        Ext.getStore('storePayControl').load();

                    };

                    var functionFailure = function () {
                        var jsonData = trex.getInfoDataBridge(apiController);
                        trex.showInfo(jsonData, 'error', 'tfCompany');
                    };

                    trex.doDataBridge(objJsonRequest,
                        functionSuccess,
                        null,
                        functionFailure,
                        null);

                }
                else {

                    trex.message('error',
                        'Incomplete Form',
                        'You must fill the required fields');
                }
            },
            columnWidth: 1,
            height: 200,
            id: 'formPay',
            itemId: 'formPay',
            width: 838,
            layout: 'column',
            bodyPadding: 10,
            items: [
                {
                    xtype: 'fieldset',
                    columnWidth: 1,
                    height: 175,
                    id: 'fieldsetPayInformation',
                    itemId: 'fieldsetPayInformation',
                    width: 816,
                    layout: 'column',
                    title: '<b>General information</b>',
                    items: [
                        {
                            xtype: 'textfield',
                            columnWidth: 0.33,
                            disabledCls: 'disabledField',
                            id: 'tfInvoice2',
                            itemId: 'tfInvoice2',
                            margin: '0 5 5 5',
                            fieldLabel: 'Invoice',
                            labelClsExtra: 'requiredField',
                            allowBlank: false
                        },
                        {
                            xtype: 'datefield',
                            columnWidth: 0.33,
                            disabledCls: 'disabledField',
                            id: 'dtInvoiceDate',
                            itemId: 'dtInvoiceDate',
                            margin: '0 5 5 5',
                            width: 150,
                            fieldLabel: 'Invoice Date',
                            labelClsExtra: 'requiredField',
                            allowBlank: false
                        },
                        {
                            xtype: 'textfield',
                            columnWidth: 0.34,
                            disabledCls: 'disabledField',
                            id: 'tfAmount2',
                            itemId: 'tfAmount1',
                            margin: '0 5 5 5',
                            fieldLabel: 'Amount',
                            labelClsExtra: 'requiredField',
                            labelWidth: 90,
                            allowBlank: false
                        },
                        {
                            xtype: 'textfield',
                            columnWidth: 1,
                            disabledCls: 'disabledField',
                            id: 'tfTax1',
                            itemId: 'tfTax',
                            margin: '0 5 5 560',
                            fieldLabel: 'Tax',
                            labelWidth: 60,
                            allowBlank: false
                        },
                        {
                            xtype: 'textfield',
                            columnWidth: 1,
                            disabledCls: 'disabledField',
                            id: 'tfTotal1',
                            itemId: 'tfTotal',
                            margin: '0 5 5 560',
                            fieldLabel: 'Total',
                            labelClsExtra: 'requiredField',
                            labelWidth: 60,
                            allowBlank: false
                        },
                        {
                            xtype: 'textareafield',
                            columnWidth: 1,
                            disabledCls: 'disabledField',
                            id: 'tfNote1',
                            itemId: 'tfNote',
                            margin: '0 5 5 5',
                            fieldLabel: 'Note',
                            labelClsExtra: 'requiredField',
                            labelWidth: 120,
                            allowBlank: false
                        }
                    ]
                }
            ]
        }
    ],
    dockedItems: [
        {
            xtype: 'toolbar',
            dock: 'top',
            id: 'toolbarPayControl',
            itemId: 'toolbarPayControl',
            items: [
                {
                    xtype: 'button',
                    handler: function (button, e) {
                        Ext.getCmp('formPayControl').confirmRecord();
                    },
                    id: 'btnConfirmPayControl',
                    itemId: 'btnConfirmPayControl',
                    width: 120,
                    iconCls: 'ion-checkmark-circled icon16',
                    text: 'Confirm',
                    textAlign: 'left'
                },
                {
                    xtype: 'tbfill',
                    id: 'filPay',
                    itemId: 'filPay'
                },
                {
                    xtype: 'button',
                    handler: function (button, e) {
                        var winPayControl = Ext.getCmp('winPayControl');
                        winPayControl.close();
                    },
                    id: 'btnClosePayControl',
                    itemId: 'btnClosePayControl',
                    width: 120,
                    iconCls: 'ion-close-circled icon16',
                    text: 'Close',
                    textAlign: 'left'
                }
            ]
        }
    ]

});