/*
 * File: app/model/modUsers.js
 *
 * This file was generated by Sencha Architect version 3.5.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('catUser.model.modUsers', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.field.Field'
    ],

    fields: [
        {
            name: 'name'
        },
        {
            name: 'last_name'
        },
        {
            name: 'password'
        },
        {
            name: 'address'
        },
        {
            name: 'location'
        },
        {
            name: 'region'
        },
        {
            name: 'city'
        },
        {
            name: 'postal_code'
        },
        {
            name: 'telephone_desk'
        },
        {
            name: 'telephone_mobile'
        },
        {
            name: 'email'
        },
        {
            name: 'birth_date'
        },
        {
            name: 'created_at'
        },
        {
            name: 'profile_id'
        },
        {
            name: 'photo_url'
        },
        {
            name: 'active'
        },
        {
            name: 'inactive_date'
        }
    ]
});