/*
 * File: app/view/winSerDetail.js
 *
 * This file was generated by Sencha Architect version 3.5.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('proServices.view.winSerDetail', {
    extend: 'Ext.window.Window',
    alias: 'widget.winSerDetail',

    requires: [
        'proServices.view.winSerDetailViewModel',
        'Ext.form.Panel',
        'Ext.form.FieldSet',
        'Ext.form.field.Date',
        'Ext.form.field.ComboBox',
        'Ext.form.field.Checkbox',
        'Ext.toolbar.Toolbar',
        'Ext.button.Button',
        'Ext.toolbar.Fill'
    ],

    viewModel: {
        type: 'winserdetail'
    },
    height: 330,
    id: 'winSerDetail',
    itemId: 'winserDetail',
    maxHeight: 350,
    minHeight: 500,
    ui: 'green-window',
    width: 850,
    layout: 'column',
    closable: false,
    title: 'Service Detail',
    modal: true,

    items: [
        {
            xtype: 'form',
            confirmRecord: function () {
                if (Ext.getCmp('formSerDetail').isValid()) {
                    var formRecord = 'formSerDetail';
                    var apiController = 'apiSerDetail';
                    var apiMethod = 'createSerDetail';

                    var objJsonRequest = new Object();
                    objJsonRequest.apiController = apiController;
                    objJsonRequest.apiMethod = apiMethod;
                    objJsonRequest.apiData = trex.prepareFormFields(formRecord);

                    var functionSuccess = function () {
                        var jsonData = trex.getInfoDataBridge(apiController);

                        trex.showInfo(jsonData, 'information');

                        var winSerDetail = Ext.getCmp('winSerDetail');
                        winSerDetail.close();

                        Ext.getStore('storeSerDetail').load();

                    };

                    var functionFailure = function () {
                        var jsonData = trex.getInfoDataBridge(apiController);
                        trex.showInfo(jsonData, 'error', 'tfCompany');
                    };

                    trex.doDataBridge(objJsonRequest,
                        functionSuccess,
                        null,
                        functionFailure,
                        null);

                }
                else {

                    trex.message('error',
                        'Incomplete Form',
                        'You must fill the required fields');
                }
            },
            columnWidth: 1,
            height: 268,
            id: 'formSerDetail',
            itemId: 'formSerDetail',
            width: 838,
            layout: 'column',
            bodyPadding: 10,
            items: [
                {
                    xtype: 'fieldset',
                    columnWidth: 1,
                    height: 103,
                    id: 'fieldsetSerDetailInformation',
                    itemId: 'fieldsetSerDetailInformation',
                    width: 816,
                    layout: 'column',
                    title: '<b>General information</b>',
                    items: [
                        {
                            xtype: 'textfield',
                            columnWidth: 0.33,
                            disabledCls: 'disabledField',
                            id: 'tfNumService',
                            itemId: 'tfNumService',
                            margin: '0 5 5 5',
                            fieldLabel: 'Num service',
                            labelClsExtra: 'requiredField',
                            allowBlank: false
                        },
                        {
                            xtype: 'datefield',
                            columnWidth: 0.33,
                            disabledCls: 'disabledField',
                            id: 'dtDateService',
                            itemId: 'dtDateService',
                            margin: '0 5 5 5',
                            fieldLabel: 'Service Date',
                            labelClsExtra: 'requiredField',
                            allowBlank: false
                        },
                        {
                            xtype: 'combobox',
                            columnWidth: 0.33,
                            disabledCls: 'disabledField',
                            id: 'cbPeriod',
                            itemId: 'cbPeriod',
                            margin: '0 5 5 5',
                            width: 387,
                            fieldLabel: 'Period',
                            labelClsExtra: 'requiredField',
                            labelWidth: 80,
                            allowBlank: false
                        },
                        {
                            xtype: 'combobox',
                            columnWidth: 0.33,
                            disabledCls: 'disabledField',
                            id: 'cbCustomerID',
                            itemId: 'cbCustomerID',
                            margin: '0 5 5 5',
                            width: 387,
                            fieldLabel: 'Customer',
                            labelClsExtra: 'requiredField',
                            labelWidth: 70,
                            allowBlank: false
                        },
                        {
                            xtype: 'combobox',
                            columnWidth: 0.33,
                            disabledCls: 'disabledField',
                            id: 'cbBranchOffice',
                            itemId: 'cbBranchOffice',
                            margin: '0 5 5 5',
                            width: 387,
                            fieldLabel: 'Branch Office',
                            labelClsExtra: 'requiredField',
                            allowBlank: false
                        },
                        {
                            xtype: 'textfield',
                            columnWidth: 0.33,
                            disabledCls: 'disabledField',
                            id: 'tfAuthorizer',
                            itemId: 'tfAuthorizer',
                            margin: '0 5 5 5',
                            fieldLabel: 'Authorizer',
                            labelClsExtra: 'requiredField',
                            labelWidth: 80,
                            allowBlank: false
                        },
                        {
                            xtype: 'textfield',
                            columnWidth: 0.33,
                            disabledCls: 'disabledField',
                            id: 'tfStatus',
                            itemId: 'tfStatus',
                            margin: '0 5 5 5',
                            fieldLabel: 'Status',
                            labelClsExtra: 'requiredField',
                            allowBlank: false
                        }
                    ]
                },
                {
                    xtype: 'fieldset',
                    columnWidth: 1,
                    height: 57,
                    id: 'fieldsetFromToInformation',
                    itemId: 'fieldsetFromToInformation',
                    maxHeight: 150,
                    width: 816,
                    layout: 'column',
                    title: '<b>From-To</b>',
                    items: [
                        {
                            xtype: 'combobox',
                            columnWidth: 0.4,
                            disabledCls: 'disabledField',
                            id: 'cbSector',
                            itemId: 'cbSector',
                            margin: '0 5 5 5',
                            width: 387,
                            fieldLabel: 'Sector',
                            labelClsExtra: 'requiredField',
                            labelWidth: 80,
                            allowBlank: false
                        },
                        {
                            xtype: 'combobox',
                            columnWidth: 0.4,
                            disabledCls: 'disabledField',
                            id: 'cbZone',
                            itemId: 'cbZone',
                            margin: '0 5 5 5',
                            width: 387,
                            fieldLabel: 'Zone',
                            labelClsExtra: 'requiredField',
                            labelWidth: 70,
                            allowBlank: false
                        },
                        {
                            xtype: 'textfield',
                            columnWidth: 0.2,
                            disabledCls: 'disabledField',
                            id: 'tfCost',
                            itemId: 'tfCost',
                            margin: '0 5 5 5',
                            fieldLabel: 'Cost',
                            labelClsExtra: 'requiredField',
                            labelWidth: 40,
                            allowBlank: false
                        }
                    ]
                },
                {
                    xtype: 'fieldset',
                    columnWidth: 1,
                    height: 56,
                    id: 'fieldsetAppointmentInformation',
                    itemId: 'fieldsetAppointmentInformation',
                    maxHeight: 150,
                    width: 816,
                    layout: 'column',
                    title: '<b>Appointment</b>',
                    items: [
                        {
                            xtype: 'checkboxfield',
                            columnWidth: 0.2,
                            margin: '0 5 5 5 ',
                            fieldLabel: '',
                            boxLabel: 'Appointment'
                        },
                        {
                            xtype: 'datefield',
                            columnWidth: 0.35,
                            disabledCls: 'disabledField',
                            id: 'cbAppointmentDate2',
                            itemId: 'cbAppointmentDate2',
                            margin: '0 5 5 5',
                            width: 387,
                            fieldLabel: 'Appointment Date',
                            labelClsExtra: 'requiredField',
                            labelWidth: 130,
                            allowBlank: false
                        },
                        {
                            xtype: 'textfield',
                            columnWidth: 0.35,
                            disabledCls: 'disabledField',
                            id: 'tfAppointmentHour2',
                            itemId: 'tfAppointmentHour2',
                            margin: '0 5 5 5',
                            width: 387,
                            fieldLabel: 'Appointment Hour',
                            labelClsExtra: 'requiredField',
                            labelWidth: 130,
                            allowBlank: false
                        }
                    ]
                }
            ]
        }
    ],
    dockedItems: [
        {
            xtype: 'toolbar',
            dock: 'top',
            id: 'toolbarSerDetail',
            itemId: 'toolbarSerDetail',
            items: [
                {
                    xtype: 'button',
                    handler: function (button, e) {
                        Ext.getCmp('formSerDetail').confirmRecord();
                    },
                    id: 'btnConfirmSerDetail',
                    itemId: 'btnConfirmSerDetail',
                    width: 120,
                    iconCls: 'ion-checkmark-circled icon16',
                    text: 'Confirm',
                    textAlign: 'left'
                },
                {
                    xtype: 'tbfill',
                    id: 'filSerDetail',
                    itemId: 'filSerDetail'
                },
                {
                    xtype: 'button',
                    handler: function (button, e) {
                        var winSerDetail = Ext.getCmp('winSerDetail');
                        winSerDetail.close();
                    },
                    id: 'btnCloseSerDetail',
                    itemId: 'btnCloseSerDetail',
                    width: 120,
                    iconCls: 'ion-close-circled icon16',
                    text: 'Close',
                    textAlign: 'left'
                }
            ]
        }
    ]

});