/*
 * File: app/store/storeEventCar.js
 *
 * This file was generated by Sencha Architect version 3.5.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('catCar.store.storeEventCar', {
    extend: 'Ext.data.Store',

    requires: [
        'catCar.model.modEventCar',
        'Ext.data.proxy.Rest',
        'Ext.data.reader.Json'
    ],

    constructor: function (cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            storeId: 'storeEventCar',
            model: 'catCar.model.modEventCar',
            proxy: {
                type: 'rest',
                url: '',
                reader: {
                    type: 'json',
                    rootProperty: 'eventCars',
                    totalProperty: 'numEventCars.total'
                }
            },
            listeners: {
                beforeload: {
                    fn: me.onStoreBeforeLoad,
                    scope: me
                }
            }
        }, cfg)]);
    },

    onStoreBeforeLoad: function (store, operation, eOpts) {
        var storeEventCar = Ext.getStore('storeEventCar');
        var proxySector = storeEventCar.getProxy();

        var objJsonData = new Object();
        objJsonData.page = storeEventCar.currentPage;
        objJsonData.start = (storeEventCar.currentPage - 1) * storeEventCar.pageSize;
        objJsonData.limit = storeEventCar.pageSize;

        var objJsonRequest = new Object();
        objJsonRequest.apiController = 'apiEventCar';
        objJsonRequest.apiMethod = 'listEventCar';
        objJsonRequest.apiData = JSON.stringify(objJsonData);

        proxySector.api.read = '../../backend/public/dataBridge/' + objJsonRequest.apiController;
        proxySector.extraParams = objJsonRequest;

    }

});