/*
 * File: app/view/MyForm.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('appBase.view.MyForm', {
    extend: 'Ext.form.Panel',
    alias: 'widget.myform',

    requires: [
        'appBase.view.MyFormViewModel',
        'Ext.button.Button'
    ],

    viewModel: {
        type: 'myform'
    },
    height: 250,
    width: 400,
    bodyPadding: 10,
    title: 'My Form',

    items: [
        {
            xtype: 'button',
            text: 'eqwd'
        }
    ]

});