/*
 * File: app/view/winUsers.js
 *
 * This file was generated by Sencha Architect version 3.5.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('catUser.view.winUsers', {
    extend: 'Ext.window.Window',
    alias: 'widget.winUsers',

    requires: [
        'catUser.view.winUsersViewModel',
        'Ext.form.Panel',
        'Ext.form.FieldSet',
        'Ext.form.field.Date',
        'Ext.form.RadioGroup',
        'Ext.form.field.Radio',
        'Ext.form.field.ComboBox',
        'Ext.form.field.File',
        'Ext.form.field.TextArea',
        'Ext.toolbar.Toolbar',
        'Ext.button.Button',
        'Ext.toolbar.Fill'
    ],

    viewModel: {
        type: 'winusers'
    },
    height: 470,
    id: 'winUsers',
    itemId: 'winUsers',
    minHeight: 400,
    minWidth: 850,
    ui: 'green-window',
    width: 850,
    layout: 'column',
    closable: false,
    title: 'Users',
    modal: true,

    items: [
        {
            xtype: 'form',
            confirmRecord: function () {
                if (Ext.getCmp('formUsers').isValid()) {
                    var formRecord = 'formUsers';
                    var apiController = 'apiUser';
                    var apiMethod = 'storeUser';

                    var objJsonRequest = new Object();
                    objJsonRequest.apiController = apiController;
                    objJsonRequest.apiMethod = apiMethod;
                    objJsonRequest.apiData = trex.prepareFormFields(formRecord);

                    var functionSuccess = function () {
                        var jsonData = trex.getInfoDataBridge(apiController);

                        trex.showInfo(jsonData, 'information');

                        var winUsers = Ext.getCmp('winUsers');
                        winUsers.close();

                        Ext.getStore('storeUsers').load();

                    };

                    var functionFailure = function () {
                        var jsonData = trex.getInfoDataBridge(apiController);
                        trex.showInfo(jsonData, 'error', 'tfCompany');
                    };

                    trex.doDataBridge(objJsonRequest,
                        functionSuccess,
                        null,
                        functionFailure,
                        null);

                }
                else {

                    trex.message('error',
                        'Incomplete Form',
                        'You must fill the required fields');
                }
            },
            columnWidth: 1,
            height: 410,
            id: 'formUsers',
            itemId: 'formUsers',
            width: 838,
            layout: 'column',
            bodyPadding: 10,
            items: [
                {
                    xtype: 'fieldset',
                    columnWidth: 1,
                    height: 184,
                    id: 'fieldsetUsersInformation',
                    itemId: 'fieldsetUsersInformation',
                    width: 816,
                    layout: 'column',
                    title: '<b>General information</b>',
                    items: [
                        {
                            xtype: 'textfield',
                            columnWidth: 0.5,
                            disabledCls: 'disabledField',
                            id: 'tfLastName',
                            itemId: 'tfLastName',
                            margin: '0 5 5 5',
                            width: 387,
                            fieldLabel: 'Last Name',
                            labelClsExtra: 'requiredField',
                            allowBlank: false
                        },
                        {
                            xtype: 'textfield',
                            columnWidth: 0.5,
                            disabledCls: 'disabledField',
                            id: 'tfName',
                            itemId: 'tfName',
                            margin: '0 5 5 5',
                            fieldLabel: 'Name',
                            labelClsExtra: 'requiredField',
                            allowBlank: false
                        },
                        {
                            xtype: 'datefield',
                            columnWidth: 0.33,
                            disabledCls: 'disabledField',
                            id: 'dtCreatedAt',
                            itemId: 'dtCreatedAt',
                            margin: '0 5 5 5',
                            fieldLabel: 'Created',
                            allowBlank: false
                        },
                        {
                            xtype: 'checkboxfield',
                            columnWidth: 0.17,
                            disabledCls: 'disabledField',
                            id: 'chActive',
                            itemId: 'chActive',
                            margin: '0 5 5 5',
                            boxLabel: 'Active'
                        },
                        {
                            xtype: 'datefield',
                            columnWidth: 0.33,
                            disabledCls: 'disabledField',
                            id: 'dtBirthDate',
                            itemId: 'dtBirthDate',
                            margin: '0 5 5 5',
                            width: 228,
                            fieldLabel: 'Birth Date',
                            allowBlank: false
                        },
                        {
                            xtype: 'radiogroup',
                            columnWidth: 0.41,
                            disabledCls: 'disabledField',
                            id: 'rgGender',
                            itemId: 'rgGender',
                            margin: '0 5 5 5',
                            width: 300,
                            fieldLabel: 'Gender',
                            items: [
                                {
                                    xtype: 'radiofield',
                                    disabledCls: 'disabledRadio',
                                    id: 'rbMale',
                                    itemId: 'rbMale',
                                    name: 'rgGender',
                                    boxLabel: 'Male',
                                    checked: true,
                                    inputValue: 'Male'
                                },
                                {
                                    xtype: 'radiofield',
                                    disabledCls: 'disabledRadio',
                                    id: 'rbFemale',
                                    itemId: 'rbFemale',
                                    name: 'rgGender',
                                    boxLabel: 'Female',
                                    inputValue: 'Female'
                                }
                            ]
                        },
                        {
                            xtype: 'radiogroup',
                            columnWidth: 0.78,
                            shim: false,
                            disabledCls: 'disabledField',
                            id: 'rgCivilStatus',
                            itemId: 'rgCivilStatus',
                            margin: '0  5 5 5',
                            width: 300,
                            referenceHolder: false,
                            fieldLabel: 'Civil Status',
                            items: [
                                {
                                    xtype: 'radiofield',
                                    disabledCls: 'disabledRadio',
                                    id: 'rbMarried',
                                    itemId: 'rbMarried',
                                    name: 'rgCivilStatus',
                                    boxLabel: 'Married',
                                    inputValue: 'Married'
                                },
                                {
                                    xtype: 'radiofield',
                                    disabledCls: 'disabledRadio',
                                    id: 'rbSingle',
                                    itemId: 'rbSingle',
                                    name: 'rgCivilStatus',
                                    boxLabel: 'Single',
                                    inputValue: 'Single'
                                },
                                {
                                    xtype: 'radiofield',
                                    disabledCls: 'disabledRadio',
                                    id: 'rbDivorced',
                                    itemId: 'rbDivorced',
                                    name: 'rgCivilStatus',
                                    boxLabel: 'Divorced',
                                    inputValue: 'Divorced'
                                },
                                {
                                    xtype: 'radiofield',
                                    disabledCls: 'disabledRadio',
                                    id: 'rbWidowed',
                                    itemId: 'rbWidowed',
                                    name: 'rgCivilStatus',
                                    boxLabel: 'Widowed',
                                    inputValue: 'Widowed'
                                },
                                {
                                    xtype: 'radiofield',
                                    disabledCls: 'disabledRadio',
                                    id: 'rbNone',
                                    itemId: 'rbNone',
                                    name: 'rgCivilStatus',
                                    boxLabel: 'None',
                                    checked: true,
                                    inputValue: 'None'
                                }
                            ]
                        },
                        {
                            xtype: 'textfield',
                            columnWidth: 0.4,
                            disabledCls: 'disabledField',
                            id: 'tfEmail',
                            itemId: 'tfEmail',
                            margin: '0 5 5 5',
                            fieldLabel: 'Email',
                            labelClsExtra: 'requiredField',
                            allowBlank: false
                        },
                        {
                            xtype: 'textfield',
                            columnWidth: 0.3,
                            disabledCls: 'disabledField',
                            id: 'tfPassword',
                            itemId: 'tfPassword',
                            margin: '0 5 5 5',
                            fieldLabel: 'Password',
                            labelWidth: 65,
                            inputType: 'password',
                            allowBlank: false
                        },
                        {
                            xtype: 'textfield',
                            columnWidth: 0.3,
                            disabledCls: 'disabledField',
                            id: 'tfPassConf',
                            itemId: 'tfPassConf',
                            margin: '0 5 5 5',
                            fieldLabel: 'Conf. Pass',
                            labelWidth: 68,
                            inputType: 'password',
                            allowBlank: false
                        },
                        {
                            xtype: 'combobox',
                            columnWidth: 0.4,
                            id: 'tfProfileCode',
                            itemId: 'tfProfileCode',
                            margin: '0 5 5 5 ',
                            fieldLabel: 'Profile',
                            displayField: 'profile_description',
                            store: 'storeProfiles',
                            valueField: 'profile_code'
                        },
                        {
                            xtype: 'textfield',
                            columnWidth: 0.3,
                            disabledCls: 'disabledField',
                            id: 'tfTelephoneDesk',
                            itemId: 'tfTelephoneDesk',
                            margin: '0 5 5 5',
                            fieldLabel: 'Telephone',
                            allowBlank: false
                        },
                        {
                            xtype: 'textfield',
                            columnWidth: 0.3,
                            disabledCls: 'disabledField',
                            id: 'tfTelephoneMobile',
                            itemId: 'tfTelephoneMobile',
                            margin: '0 5 5 5',
                            fieldLabel: 'Mobile',
                            allowBlank: false
                        }
                    ]
                },
                {
                    xtype: 'fieldset',
                    columnWidth: 1,
                    id: 'fieldsetAddress',
                    itemId: 'fieldsetAddress',
                    layout: 'column',
                    title: '<b>Address</b>',
                    items: [
                        {
                            xtype: 'textfield',
                            columnWidth: 1,
                            disabledCls: 'disabledField',
                            id: 'tfAddress',
                            itemId: 'tfAddress',
                            margin: '0 5 5 5',
                            fieldLabel: 'Address',
                            labelClsExtra: 'requiredField',
                            allowBlank: false
                        },
                        {
                            xtype: 'textfield',
                            columnWidth: 0.33,
                            disabledCls: 'disabledField',
                            id: 'tfZipCode',
                            itemId: 'tfZipCode',
                            margin: '0 5 5 5',
                            fieldLabel: 'Zip Code',
                            labelClsExtra: 'requiredField',
                            allowBlank: false
                        },
                        {
                            xtype: 'textfield',
                            columnWidth: 0.33,
                            disabledCls: 'disabledField',
                            id: 'tfLocation',
                            itemId: 'tfLocation',
                            margin: '0 5 5 5',
                            fieldLabel: 'Location',
                            labelClsExtra: 'requiredField',
                            allowBlank: false
                        },
                        {
                            xtype: 'textfield',
                            columnWidth: 0.33,
                            disabledCls: 'disabledField',
                            id: 'tfRegion',
                            itemId: 'tfRegion',
                            margin: '0 5 5 5',
                            fieldLabel: 'Region',
                            labelClsExtra: 'requiredField',
                            allowBlank: false
                        },
                        {
                            xtype: 'textfield',
                            columnWidth: 0.33,
                            disabledCls: 'disabledField',
                            id: 'tfCity',
                            itemId: 'tfCity',
                            margin: '0 5 5 5',
                            fieldLabel: 'City',
                            labelClsExtra: 'requiredField',
                            allowBlank: false
                        },
                        {
                            xtype: 'textfield',
                            columnWidth: 0.33,
                            disabledCls: 'disabledField',
                            id: 'tfStateCode',
                            itemId: 'tfStateCode',
                            margin: '0 5 5 5',
                            fieldLabel: 'State',
                            labelClsExtra: 'requiredField',
                            allowBlank: false
                        },
                        {
                            xtype: 'textfield',
                            columnWidth: 0.33,
                            disabledCls: 'disabledField',
                            id: 'tfCountryCode',
                            itemId: 'tfCountryCode',
                            margin: '0 5 5 5',
                            fieldLabel: 'Country',
                            labelClsExtra: 'requiredField',
                            allowBlank: false
                        }
                    ]
                },
                {
                    xtype: 'fieldset',
                    columnWidth: 1,
                    height: 85,
                    id: 'fieldsetGeolocalization',
                    itemId: 'fieldsetGeolocalization',
                    layout: 'column',
                    title: '<b>Geolocalization</b>',
                    items: [
                        {
                            xtype: 'textfield',
                            columnWidth: 0.5,
                            disabledCls: 'disabledField',
                            id: 'tfLatitude',
                            itemId: 'tfLatitude',
                            margin: '0 5 5 5',
                            fieldLabel: 'Latitude',
                            labelClsExtra: ''
                        },
                        {
                            xtype: 'textfield',
                            columnWidth: 0.5,
                            disabledCls: 'disabledField',
                            id: 'tfLongitude',
                            itemId: 'tfLongitude',
                            margin: '0 5 5 5',
                            fieldLabel: 'Longitude',
                            labelClsExtra: ''
                        },
                        {
                            xtype: 'textfield',
                            columnWidth: 1,
                            disabledCls: 'disabledField',
                            id: 'tfGeocodeUrl',
                            itemId: 'tfGeocodeUrl',
                            margin: '0 5 5 5',
                            fieldLabel: 'Geocode URL'
                        }
                    ]
                },
                {
                    xtype: 'fieldset',
                    columnWidth: 1,
                    height: 139,
                    hidden: true,
                    id: 'fieldsetPhoto',
                    itemId: 'fieldsetPhoto',
                    layout: 'column',
                    title: '<b>Photo</b>',
                    items: [
                        {
                            xtype: 'filefield',
                            columnWidth: 0.75,
                            id: 'tfPhoto',
                            itemId: 'tfPhoto',
                            margin: '35 5 5 5 ',
                            fieldLabel: 'Photo'
                        },
                        {
                            xtype: 'textareafield',
                            columnWidth: 0.2,
                            height: 108,
                            width: 238,
                            fieldLabel: '',
                            labelWidth: 0
                        }
                    ]
                }
            ]
        }
    ],
    dockedItems: [
        {
            xtype: 'toolbar',
            dock: 'top',
            id: 'toolbarUsers',
            itemId: 'toolbarUsers',
            items: [
                {
                    xtype: 'button',
                    handler: function (button, e) {
                        Ext.getCmp('formUsers').confirmRecord();
                    },
                    id: 'btnConfirmUsers',
                    itemId: 'btnConfirmUsers',
                    width: 120,
                    iconCls: 'ion-checkmark-circled icon16',
                    text: 'Confirm',
                    textAlign: 'left'
                },
                {
                    xtype: 'tbfill',
                    id: 'filUsers',
                    itemId: 'filUsers'
                },
                {
                    xtype: 'button',
                    handler: function (button, e) {
                        var winUsers = Ext.getCmp('winUsers');
                        winUsers.close();
                    },
                    id: 'btnCloseUsers',
                    itemId: 'btnCloseUsers',
                    width: 120,
                    iconCls: 'ion-close-circled icon16',
                    text: 'Close',
                    textAlign: 'left'
                }
            ]
        }
    ]

});