/*
 * File: app.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

// @require @packageOverrides
Ext.Loader.setConfig({
    enabled: true
});


Ext.application({
    views: [
        'winAcceso',
        'winResetAcceso',
        'MyWindow1'
    ],
    name: 'acceso',

    launch: function() {
        Ext.create('acceso.view.winAcceso', {renderTo: Ext.getBody()});
        //http://www.kunal-chowdhury.com/2012/10/how-to-update-application-cache-programmatically-in-html5.html
        var applicationCache = window.applicationCache;

        switch (applicationCache.status) {
          case applicationCache.UNCACHED: // UNCACHED = 0
            console.log('UNCACHED');
            break;
          case applicationCache.IDLE: // IDLE = 1
            console.log('IDLE');
            break;
          case applicationCache.CHECKING: // CHECKING = 2
            console.log('CHECKING');
            break;
          case applicationCache.DOWNLOADING: // DOWNLOADING = 3
            console.log('DOWNLOADING');
            break;
          case applicationCache.UPDATEREADY:  // UPDATEREADY = 4
            console.log('UPDATEREADY');
            break;
          case applicationCache.OBSOLETE: // OBSOLETE = 5
            console.log('OBSOLETE');
            break;
          default:
            console.log('UKNOWN CACHE STATUS');
            break;
        }

        if(applicationCache.status !== applicationCache.UNCACHED){
            applicationCache.update(); // Take an attempt to update the user's cache.
            if (applicationCache.status == window.applicationCache.UPDATEREADY) {
                applicationCache.swapCache();  // The fetch was successful, swap to the new cache.
                if (confirm('Una nueva versión de ésta aplicación está disponible. Desea cargarla?')) {
                    window.location.reload();
                }
            }
        }

        appLocal = this.getApplication();
        aplicacionLocal = this;

        var tituloAplicacion = datosOpenLink('tituloAplicacion');
        Ext.getDoc().dom.title = tituloAplicacion;

        var nombreSistema = configuracionSistema('nombreSistema');
        nombreSistema = nombreSistema + ' (Liberación: ' + releaseActiva() + ')';

        Ext.getCmp('winAcceso').setTitle(nombreSistema);

        var iconoAplicacion = datosOpenLink('servidorWeb');
        iconoAplicacion = iconoAplicacion + 'copamex/framework/ambiente/ambiente.ico';

        cambiaFavicon(iconoAplicacion);

        appLocal.ajustaInterface();
        asignaValorElemento('txtAmbienteActivo',datosOpenLink('ambiente'));
    },

    accederSistema: function() {
        var indDatosValidos = true;

        var f_clave  = leeValorElemento('p_clavePersona');
        var f_acceso = leeValorElemento('p_acceso');

        if (f_clave === '' || f_acceso === ''){
            mensajeUsr("ERROR",
                      "Información requerida",
                      "Debe ingresar Usuario y Contraseña");

            indDatosValidos = false;
        }

        if(indDatosValidos){

            arrayInformacion = new Array();
            arrayInformacion[0] = new Object();
            arrayInformacion[0].codSistema        = configuracionSistema('codSistema');
            arrayInformacion[0].clavePersona      = f_clave;
            arrayInformacion[0].acceso            = f_acceso;
            arrayInformacion[0].codEmpresaActiva  = configuracionSistema('codEmpresaActiva');
            arrayInformacion[0].codSucursalActiva = configuracionSistema('codSucursalActiva');
            arrayInformacion[0].openLinkServidor  = datosOpenLink('servidor');
            arrayInformacion[0].openLinkServicio  = datosOpenLink('servicio');
            arrayInformacion[0].openLinkPrograma  = datosOpenLink('programa');

            var strJson = JSON.stringify(arrayInformacion);

            var datosJsonFormulario = {codPrograma       : "api_AccesoPortal",
                                       codProcedimiento  : "validaAcceso",
                                       tipoLlamada       : "formulario",
                                       usuarioActivo     : f_clave,
                                       datosJson         : strJson,
                                       codEmpresa        : configuracionSistema('codEmpresa'),
                                       codSistema        : configuracionSistema('codSistema'),
                                       codEmpresaActiva  : configuracionSistema('codEmpresaActiva'),
                                       codSucursalActiva : configuracionSistema('codSucursalActiva'),
                                       openLinkServidor  : datosOpenLink('servidor'),
                                       openLinkServicio  : datosOpenLink('servicio'),
                                       openLinkPrograma  : datosOpenLink('programa')
                                       };

            deshabilitaElemento('p_clavePersona');
            deshabilitaElemento('p_acceso');
            deshabilitaElemento('btnAcceder');

            var cajaEspera = Ext.MessageBox.show({
                msg: 'Por favor espere, se están validando sus credenciales...',
                progressText: 'Validando Acceso',
                width:400,
                wait:true,
                waitConfig: {interval:170}
            });

            Ext.Ajax.request({
                url: '../../../../../../openLink/openLink.jsp',
                method: 'POST',
                success: function(response,opts){
                    /* ECRC: Función cuando se ejecuta correctamente el Script en el Servidor */
                    var datosJson = Ext.decode(response.responseText);

                    if(datosJson.success === true ){
                        /* ECRC: API ejecutada correctamente y sin Errores */

                        var temp_datos_sesion = datosJson.temp_datos_sesion[0];
                        var mensajeAcceso = '';

                        var cajaEspera = Ext.MessageBox.show({
                            msg: 'Por favor espere mientras es direccionado al Menú Principal.',
                            progressText: 'Acceso Correcto',
                            width:400,
                            wait:true,
                            waitConfig: {interval:170}
                        });
                        generaSesion(temp_datos_sesion);
                        window.open(configuracionSistema('portal'),'_self','toolbar=no');

                    }
                    else{
                        /* ECRC: Errores encontrados en la API */
                        var aMensaje = datosJson.temp_mensaje;
                        var mensajeError = "";

                        for(var iCiclo = 0; iCiclo<aMensaje.length; iCiclo++){
                            mensajeError += aMensaje[iCiclo].mensaje + "</br></br>";
                        }

                        habilitaElemento('p_clavePersona');
                        habilitaElemento('p_acceso');
                        habilitaElemento('btnAcceder');

                        mensajeUsr("ERROR",
                                   "Error de Acceso",
                                   mensajeError);
                    }
                 },
                failure: function(response,opts){
                    /* ECRC: Función cuando hay Error en la Ejecución en el Servidor */
                    console.log('Servidor falló con el Código ' + response.status);
                    habilitaElemento('p_clavePersona');
                    habilitaElemento('p_acceso');
                    habilitaElemento('btnAcceder');

                },
                params: datosJsonFormulario
            });

            cajaEspera.hide();
        }
    },

    ajustaInterface: function() {
        Ext.getCmp('formAcceso').doLayout();
    }

});
