/*
 * File: app/store/storeRageFares.js
 *
 * This file was generated by Sencha Architect version 3.5.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('catTaxiFares.store.storeRageFares', {
    extend: 'Ext.data.Store',

    requires: [
        'catTaxiFares.model.modRageFares',
        'Ext.data.proxy.Rest',
        'Ext.data.reader.Json'
    ],

    constructor: function (cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            storeId: 'storeRageFares',
            model: 'catTaxiFares.model.modRageFares',
            proxy: {
                type: 'rest',
                url: '',
                reader: {
                    type: 'json',
                    rootProperty: 'sector',
                    totalProperty: 'numSector.total'
                }
            },
            listeners: {
                beforeload: {
                    fn: me.onStoreBeforeLoad,
                    scope: me
                }
            }
        }, cfg)]);
    },

    onStoreBeforeLoad: function (store, operation, eOpts) {
        var storeSector = Ext.getStore('storeSector');
        var proxySector = storeSector.getProxy();

        var objJsonData = new Object();
        objJsonData.page = storeSector.currentPage;
        objJsonData.start = (storSector.currentPage - 1) * storeSector.pageSize;
        objJsonData.limit = storeSector.pageSize;

        var objJsonRequest = new Object();
        objJsonRequest.apiController = 'apiSector';
        objJsonRequest.apiMethod = 'listSector';
        objJsonRequest.apiData = JSON.stringify(objJsonData);

        proxySector.api.read = '../../backend/public/dataBridge/' + objJsonRequest.apiController;
        proxySector.extraParams = objJsonRequest;

    }

});