/*
 * File: app/store/storeProfiles.js
 *
 * This file was generated by Sencha Architect version 3.5.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('catUser.store.storeProfiles', {
    extend: 'Ext.data.Store',

    requires: [
        'catUser.model.modProfiles'
    ],

    constructor: function (cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            storeId: 'storeProfiles',
            model: 'catUser.model.modProfiles',
            data: [
                {
                    profile_code: 'admin',
                    profile_description: 'Administrator'
                },
                {
                    profile_code: 'driver',
                    profile_description: 'Driver'
                },
                {
                    profile_code: 'customer',
                    profile_description: 'Customer'
                }
            ]
        }, cfg)]);
    }
});