/*
 * File: app/view/winRageFares.js
 *
 * This file was generated by Sencha Architect version 3.5.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('catTaxiFares.view.winRageFares', {
    extend: 'Ext.window.Window',
    alias: 'widget.winRageFares',

    requires: [
        'catTaxiFares.view.winRangeFaresViewModel',
        'Ext.form.Panel',
        'Ext.form.FieldSet',
        'Ext.form.field.Text',
        'Ext.toolbar.Toolbar',
        'Ext.button.Button',
        'Ext.toolbar.Fill'
    ],

    viewModel: {
        type: 'winragefares'
    },
    height: 500,
    id: 'winRageFares',
    itemId: 'winRageFares',
    maxHeight: 210,
    minHeight: 500,
    minWidth: 850,
    ui: 'green-window',
    width: 850,
    layout: 'column',
    closable: false,
    title: ' Rage Fares',
    modal: true,

    items: [
        {
            xtype: 'form',
            confirmRecord: function () {
                if (Ext.getCmp('formRangeFares').isValid()) {
                    var formRecord = 'formRageFares';
                    var apiController = 'apiRageFares';
                    var apiMethod = 'createRageFares';

                    var objJsonRequest = new Object();
                    objJsonRequest.apiController = apiController;
                    objJsonRequest.apiMethod = apiMethod;
                    objJsonRequest.apiData = trex.prepareFormFields(formRecord);

                    var functionSuccess = function () {
                        var jsonData = trex.getInfoDataBridge(apiController);

                        trex.showInfo(jsonData, 'information');

                        var winRangeFares = Ext.getCmp('winRageFares');
                        winRangeFares.close();

                        Ext.getStore('storeRangeFares').load();

                    };

                    var functionFailure = function () {
                        var jsonData = trex.getInfoDataBridge(apiController);
                        trex.showInfo(jsonData, 'error', 'tfCompany');
                    };

                    trex.doDataBridge(objJsonRequest,
                        functionSuccess,
                        null,
                        functionFailure,
                        null);

                }
                else {

                    trex.message('error',
                        'Incomplete Form',
                        'You must fill the required fields');
                }
            },
            columnWidth: 1,
            height: 139,
            id: 'formRageFares',
            itemId: 'formRageFares',
            width: 838,
            layout: 'column',
            bodyPadding: 10,
            items: [
                {
                    xtype: 'fieldset',
                    columnWidth: 1,
                    height: 117,
                    id: 'fieldsetRangeFaresInformation',
                    itemId: 'fieldsetRangeFaresInformation',
                    width: 816,
                    layout: 'column',
                    title: '<b>General information</b>',
                    items: [
                        {
                            xtype: 'textfield',
                            columnWidth: 0.33,
                            disabledCls: 'disabledField',
                            id: 'tfKmStart',
                            itemId: 'tfKmStart',
                            margin: '0 5 5 5',
                            width: 387,
                            fieldLabel: 'Range Km Start',
                            labelClsExtra: 'requiredField',
                            labelWidth: 120,
                            allowBlank: false
                        },
                        {
                            xtype: 'textfield',
                            columnWidth: 0.33,
                            disabledCls: 'disabledField',
                            id: 'tfKmEnd',
                            itemId: 'tfKmEnd',
                            margin: '0 5 5 5',
                            width: 387,
                            fieldLabel: 'Km End',
                            labelClsExtra: 'requiredField',
                            allowBlank: false
                        },
                        {
                            xtype: 'textfield',
                            columnWidth: 0.33,
                            disabledCls: 'disabledField',
                            id: 'tfCost',
                            itemId: 'tfCost',
                            margin: '0 5 5 5',
                            width: 387,
                            fieldLabel: 'Cost',
                            labelClsExtra: 'requiredField',
                            allowBlank: false
                        }
                    ]
                }
            ]
        }
    ],
    dockedItems: [
        {
            xtype: 'toolbar',
            dock: 'top',
            id: 'toolbarRangeFares',
            itemId: 'toolbarRangeFares',
            items: [
                {
                    xtype: 'button',
                    handler: function (button, e) {
                        Ext.getCmp('formRangeFares').confirmRecord();
                    },
                    id: 'btnConfirmRangeFares',
                    itemId: 'btnConfirmRangeFares',
                    width: 120,
                    iconCls: 'ion-checkmark-circled icon16',
                    text: 'Confirm',
                    textAlign: 'left'
                },
                {
                    xtype: 'tbfill',
                    id: 'filRangeFares',
                    itemId: 'filRangeFares'
                },
                {
                    xtype: 'button',
                    handler: function (button, e) {
                        var winRangeFares = Ext.getCmp('winRangeFares');
                        winRangeFares.close();
                    },
                    id: 'btnCloseRangeFares',
                    itemId: 'btnCloseRangeFares',
                    width: 120,
                    iconCls: 'ion-close-circled icon16',
                    text: 'Close',
                    textAlign: 'left'
                }
            ]
        }
    ]

});