/*
 * File: app/view/winTaxiFares.js
 *
 * This file was generated by Sencha Architect version 3.5.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('catTaxiFares.view.winTaxiFares', {
    extend: 'Ext.window.Window',
    alias: 'widget.winTaxiFares',

    requires: [
        'catTaxiFares.view.winTaxiFaresViewModel',
        'Ext.form.Panel',
        'Ext.form.FieldSet',
        'Ext.form.field.ComboBox',
        'Ext.form.field.Date',
        'Ext.form.field.Checkbox',
        'Ext.toolbar.Toolbar',
        'Ext.button.Button',
        'Ext.toolbar.Fill'
    ],

    viewModel: {
        type: 'wintaxifares'
    },
    height: 200,
    id: 'winTaxiFares',
    itemId: 'winTaxiFares',
    maxHeight: 200,
    minHeight: 500,
    minWidth: 850,
    ui: 'green-window',
    width: 850,
    layout: 'column',
    closable: false,
    title: 'Fares',
    modal: true,

    items: [
        {
            xtype: 'form',
            confirmRecord: function () {
                if (Ext.getCmp('formTaxiFares').isValid()) {
                    var formRecord = 'formTaxiFares';
                    var apiController = 'apiTaxiFares';
                    var apiMethod = 'createTaxiFares';

                    var objJsonRequest = new Object();
                    objJsonRequest.apiController = apiController;
                    objJsonRequest.apiMethod = apiMethod;
                    objJsonRequest.apiData = trex.prepareFormFields(formRecord);

                    var functionSuccess = function () {
                        var jsonData = trex.getInfoDataBridge(apiController);

                        trex.showInfo(jsonData, 'information');

                        var winTaxiFares = Ext.getCmp('winTaxiFares');
                        winTaxiFares.close();

                        Ext.getStore('storeTaxiFares').load();

                    };

                    var functionFailure = function () {
                        var jsonData = trex.getInfoDataBridge(apiController);
                        trex.showInfo(jsonData, 'error', 'tfCompany');
                    };

                    trex.doDataBridge(objJsonRequest,
                        functionSuccess,
                        null,
                        functionFailure,
                        null);

                }
                else {

                    trex.message('error',
                        'Incomplete Form',
                        'You must fill the required fields');
                }
            },
            columnWidth: 1,
            height: 136,
            id: 'formTaxiFares',
            itemId: 'formTaxiFares',
            width: 838,
            layout: 'column',
            bodyPadding: 10,
            items: [
                {
                    xtype: 'fieldset',
                    columnWidth: 1,
                    height: 117,
                    id: 'fieldsetTaxiFaresInformation',
                    itemId: 'fieldsetTaxiFaresInformation',
                    width: 816,
                    layout: 'column',
                    title: '<b>General information</b>',
                    items: [
                        {
                            xtype: 'combobox',
                            columnWidth: 0.34,
                            disabledCls: 'disabledField',
                            id: 'cbTaxiTypeFare',
                            itemId: 'cbTaxiTypeFare',
                            margin: '0 5 5 5',
                            width: 387,
                            fieldLabel: 'Type Fare',
                            labelClsExtra: 'requiredField',
                            allowBlank: false
                        },
                        {
                            xtype: 'textfield',
                            columnWidth: 0.22,
                            disabledCls: 'disabledField',
                            id: 'tfTaxiStart',
                            itemId: 'tfTaxistart',
                            margin: '0 5 5 5',
                            fieldLabel: 'Start Fare',
                            labelClsExtra: 'requiredField',
                            labelWidth: 80,
                            allowBlank: false
                        },
                        {
                            xtype: 'textfield',
                            columnWidth: 0.22,
                            disabledCls: 'disabledField',
                            id: 'tfTaxiKm',
                            itemId: 'tfTaxiKm',
                            margin: '0 5 5 5',
                            fieldLabel: 'Km Fare',
                            labelClsExtra: 'requiredField',
                            labelWidth: 80,
                            allowBlank: false
                        },
                        {
                            xtype: 'textfield',
                            columnWidth: 0.22,
                            disabledCls: 'disabledField',
                            id: 'tfTaxiMin',
                            itemId: 'tfTaxiMin',
                            margin: '0 5 5 5',
                            fieldLabel: 'Min. Fare',
                            labelClsExtra: 'requiredField',
                            labelWidth: 80,
                            allowBlank: false
                        },
                        {
                            xtype: 'combobox',
                            columnWidth: 0.45,
                            disabledCls: 'disabledField',
                            id: 'cbSector',
                            itemId: 'cbSector',
                            margin: '0 5 5 5',
                            fieldLabel: 'Sector',
                            labelClsExtra: 'requiredField',
                            allowBlank: false
                        },
                        {
                            xtype: 'combobox',
                            columnWidth: 0.45,
                            disabledCls: 'disabledField',
                            id: 'cbZone',
                            itemId: 'cbZone',
                            margin: '0 5 5 5',
                            fieldLabel: 'Zone',
                            labelClsExtra: 'requiredField',
                            allowBlank: false
                        },
                        {
                            xtype: 'textfield',
                            columnWidth: 0.25,
                            disabledCls: 'disabledField',
                            id: 'tfTaxiMinWaiting',
                            itemId: 'tfTaxiMinWaiting',
                            margin: '0 5 5 5',
                            fieldLabel: 'Waiting Fare',
                            labelClsExtra: 'requiredField',
                            allowBlank: false
                        },
                        {
                            xtype: 'datefield',
                            columnWidth: 0.5,
                            disabledCls: 'disabledField',
                            id: 'dtCreatedAt',
                            itemId: 'dtCreatedAt',
                            margin: '0 5 5 165',
                            fieldLabel: 'Created',
                            labelClsExtra: 'requiredField',
                            allowBlank: false
                        },
                        {
                            xtype: 'checkboxfield',
                            columnWidth: 0.12,
                            disabledCls: 'disabledField',
                            id: 'chActive',
                            itemId: 'chActive',
                            margin: '0 5 5 5',
                            labelClsExtra: 'requiredField',
                            boxLabel: 'Active'
                        }
                    ]
                }
            ]
        }
    ],
    dockedItems: [
        {
            xtype: 'toolbar',
            dock: 'top',
            id: 'toolbarTaxiFares',
            itemId: 'toolbarTaxiFares',
            items: [
                {
                    xtype: 'button',
                    handler: function (button, e) {
                        Ext.getCmp('formTaxiFares').confirmRecord();
                    },
                    id: 'btnConfirmTaxiFares',
                    itemId: 'btnConfirmTaxiFares',
                    width: 120,
                    iconCls: 'ion-checkmark-circled icon16',
                    text: 'Confirm',
                    textAlign: 'left'
                },
                {
                    xtype: 'tbfill',
                    id: 'filTaxiFares',
                    itemId: 'filTaxiFares'
                },
                {
                    xtype: 'button',
                    handler: function (button, e) {
                        var winTaxiFares = Ext.getCmp('winTaxiFares');
                        winTaxiFares.close();
                    },
                    id: 'btnCloseTaxiFares',
                    itemId: 'btnCloseTaxiFares',
                    width: 120,
                    iconCls: 'ion-close-circled icon16',
                    text: 'Close',
                    textAlign: 'left'
                }
            ]
        }
    ]

});