/*
 * File: app/view/MyWindow1.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('acceso.view.MyWindow1', {
    extend: 'Ext.window.Window',

    requires: [
        'Ext.form.Panel'
    ],

    autoShow: true,
    closable: false,
    title: 'dd',
    titleCollapse: false,
    maximized: true,
    modal: true,

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'form',
                    bodyPadding: 10,
                    title: 'My Form'
                }
            ]
        });

        me.callParent(arguments);
    }

});