/*
 * File: app/view/winAcceso.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('acceso.view.winAcceso', {
    extend: 'Ext.window.Window',

    requires: [
        'Ext.form.Panel',
        'Ext.form.Label',
        'Ext.Img',
        'Ext.form.FieldSet',
        'Ext.form.field.Text',
        'Ext.button.Button',
        'Ext.toolbar.Toolbar',
        'Ext.toolbar.Separator',
        'Ext.toolbar.Fill'
    ],

    autoShow: true,
    draggable: false,
    id: 'winAcceso',
    itemId: 'winAcceso',
    closable: false,
    maximized: true,
    modal: true,

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'form',
                    height: 150,
                    id: 'formAmbiente',
                    itemId: 'formAmbiente',
                    layout: 'column',
                    bodyCls: 'imagenAmbiente',
                    bodyPadding: 10,
                    items: [
                        {
                            xtype: 'label',
                            columnWidth: 1,
                            formBind: false,
                            cls: 'fuenteSombraEnorme',
                            id: 'txtAmbienteActivo',
                            itemId: 'txtAmbienteActivo',
                            padding: 45,
                            text: 'Ambiente'
                        }
                    ]
                },
                {
                    xtype: 'form',
                    height: 100,
                    id: 'formEspacio01',
                    itemId: 'formEspacio01',
                    bodyPadding: 10
                },
                {
                    xtype: 'form',
                    pack: 'center',
                    autoShow: true,
                    id: 'formAcceso',
                    itemId: 'formAcceso',
                    minHeight: 350,
                    defaultAlign: 'middle',
                    layout: 'table',
                    bodyPadding: 10,
                    items: [
                        {
                            xtype: 'image',
                            colspan: 3,
                            rowspan: 1,
                            height: 150,
                            id: 'imgLogotipo',
                            itemId: 'imgLogotipo',
                            padding: '0 70 0 200',
                            src: '../../framework/terian/image/LogoCopamex.png'
                        },
                        {
                            xtype: 'fieldset',
                            colspan: 1,
                            rowspan: 2,
                            border: 0,
                            height: 150,
                            id: 'fieldsetDatosAcceso',
                            itemId: 'fieldsetDatosAcceso',
                            items: [
                                {
                                    xtype: 'textfield',
                                    id: 'p_clavePersona',
                                    itemId: 'p_clavePersona',
                                    padding: '48 0 0 0',
                                    width: 300,
                                    fieldLabel: 'Clave Usuario:',
                                    allowBlank: false,
                                    blankText: 'La Clave de Usuario es requerida',
                                    validateBlank: true
                                },
                                {
                                    xtype: 'textfield',
                                    id: 'p_acceso',
                                    itemId: 'p_acceso',
                                    width: 300,
                                    fieldLabel: 'Contraseña :',
                                    inputType: 'password',
                                    enableKeyEvents: true,
                                    listeners: {
                                        keydown: {
                                            fn: me.onP_accesoKeydown,
                                            scope: me
                                        }
                                    }
                                }
                            ]
                        },
                        {
                            xtype: 'fieldset',
                            border: 0,
                            id: 'fieldsetBotonAcceso',
                            itemId: 'fieldsetBotonAcceso',
                            items: [
                                {
                                    xtype: 'button',
                                    handler: function(button, e) {
                                        aplicacionLocal.getApplication().accederSistema();
                                    },
                                    cls: 'botonGrupoActivo',
                                    height: 53,
                                    id: 'btnAcceder',
                                    itemId: 'btnAcceder',
                                    width: 100,
                                    iconAlign: 'top',
                                    text: 'Acceder'
                                }
                            ]
                        }
                    ],
                    dockedItems: [
                        {
                            xtype: 'toolbar',
                            dock: 'bottom',
                            cls: 'colorForm',
                            id: 'toolbarBotones',
                            itemId: 'toolbarBotones',
                            items: [
                                {
                                    xtype: 'button',
                                    handler: function(button, e) {
                                        var winResetAcceso = Ext.create('widget.winResetAcceso');
                                        winResetAcceso.show();

                                    },
                                    height: 80,
                                    id: 'btnRecuperaAcceso',
                                    itemId: 'btnRecuperaAcceso',
                                    width: 100,
                                    iconAlign: 'top',
                                    iconCls: 'locked32',
                                    text: '</br>Recupera</br>Acceso',
                                    tooltip: 'Ver las actualizacion realizadas al Sistema.'
                                },
                                {
                                    xtype: 'tbseparator'
                                },
                                {
                                    xtype: 'button',
                                    handler: function(button, e) {
                                        var winReleaseSistema = Ext.getCmp('winReleaseSistema');

                                        if(!winReleaseSistema){
                                            winReleaseSistema = new Ext.Window({
                                                title : "Información de Liberación",
                                                titlebar: false,
                                                width : 850,
                                                height: 500,
                                                draggable:true,
                                                closable: false,
                                                modal: true,
                                                id: 'winReleaseSistema',
                                                layout : 'fit',
                                                items : [{
                                                    xtype : "component",
                                                    html: '<iframe src="PORTALSAC_RegistroCambios_Release201507S1.pdf" width="100%" height="100%"></iframe>'
                                                }],
                                                buttons: [

                                                {
                                                    text: 'Cerrar',
                                                    handler: function(){
                                                        winReleaseSistemaCierra();

                                                    }
                                                }
                                                ]

                                            });
                                        }

                                        winReleaseSistemaAbre();

                                        function winReleaseSistemaAbre(){
                                            winReleaseSistema.show();

                                        }

                                        function winReleaseSistemaCierra(){
                                            winReleaseSistema.close();

                                        }
                                    },
                                    height: 80,
                                    hidden: true,
                                    id: 'btnLiberacion',
                                    itemId: 'btnLiberacion',
                                    width: 100,
                                    iconAlign: 'top',
                                    iconCls: 'options32',
                                    text: '</br>Liberación</br>Julio 2015',
                                    tooltip: 'Ver las actualizacion realizadas al Sistema.'
                                },
                                {
                                    xtype: 'tbfill'
                                },
                                {
                                    xtype: 'button',
                                    handler: function(button, e) {
                                        var winSeguimientoProyecto = Ext.getCmp('winSeguimientoProyecto');

                                        if(!winSeguimientoProyecto){
                                            winSeguimientoProyecto = new Ext.Window({
                                                title : "Seguimiento del Proyecto | Portal de Clientes",
                                                titlebar: false,
                                                width : 850,
                                                height: 500,
                                                draggable:true,
                                                closable: false,
                                                maximizable: true,
                                                modal: true,
                                                id: 'winSeguimientoProyecto',
                                                layout : 'fit',
                                                items : [{
                                                    xtype : "component",
                                                    html: '<iframe src="https://tauboard.com/v/cfdf636ed74190258be333bfec41f063" width="100%" height="100%"></iframe>'
                                                }],
                                                buttons: [

                                                {
                                                    text: 'Cerrar',
                                                    handler: function(){
                                                        winSeguimientoProyectoCierra();

                                                    }
                                                }
                                                ]

                                            });
                                        }


                                        winSeguimientoProyectoAbre();

                                        function winSeguimientoProyectoAbre(){
                                            winSeguimientoProyecto.show();

                                        }

                                        function winSeguimientoProyectoCierra(){
                                            winSeguimientoProyecto.close();

                                        }
                                    },
                                    height: 80,
                                    width: 100,
                                    iconAlign: 'top',
                                    iconCls: 'library132',
                                    text: '</br>Seguimiento</br>de Proyecto',
                                    tooltip: 'Ver las actualizacion realizadas al Sistema.'
                                }
                            ]
                        }
                    ]
                }
            ],
            listeners: {
                resize: {
                    fn: me.onWinAccesoResize,
                    scope: me
                }
            }
        });

        me.callParent(arguments);
    },

    onP_accesoKeydown: function(textfield, e, eOpts) {
        if (e.getKey() === Ext.EventObject.ENTER)
        {
            aplicacionLocal.getApplication().accederSistema();
        }

    },

    onWinAccesoResize: function(window, width, height, eOpts) {
        var formAcceso = Ext.getCmp('formAcceso');
        formAcceso.doLayout();

        var alturaForm = Ext.getCmp('winAcceso').height - 290;
        Ext.getCmp('formAcceso').setHeight(alturaForm);

        var anchoForm = Ext.getCmp('winAcceso').width;
        Ext.getCmp('formEspacio01').setWidth(anchoForm);
        Ext.getCmp('formAmbiente').setWidth(anchoForm);
        Ext.getCmp('formAcceso').setWidth(anchoForm);
    }

});