/*
 * File: app/model/modCustomer.js
 *
 * This file was generated by Sencha Architect version 3.5.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('catCustomer.model.modCustomer', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.field.Field'
    ],

    fields: [
        {
            name: 'short_name'
        },
        {
            name: 'password'
        },
        {
            name: 'company'
        },
        {
            name: 'tax_id'
        },
        {
            name: 'contact_name'
        },
        {
            name: 'contact_phone'
        },
        {
            name: 'email'
        },
        {
            name: 'website'
        },
        {
            name: 'active'
        },
        {
            name: 'latitude'
        },
        {
            name: 'longitude'
        },
        {
            name: 'geocode_url'
        }
    ]
});