/*
 * File: app/view/windowMenuPrincipal.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('areaACP.view.windowMenuPrincipal', {
    extend: 'Ext.window.Window',

    requires: [
        'Ext.toolbar.Toolbar',
        'Ext.toolbar.Fill',
        'Ext.form.Panel',
        'Ext.Img',
        'Ext.form.Label',
        'Ext.tab.Panel',
        'Ext.tab.Tab'
    ],

    autoShow: true,
    draggable: false,
    id: 'windowMenuPrincipal',
    itemId: 'windowMenuPrincipal',
    layout: 'column',
    closable: false,
    maximized: true,

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'top',
                    cls: 'colorForm',
                    items: [
                        {
                            xtype: 'tbfill'
                        },
                        {
                            xtype: 'button',
                            handler: function(button, e) {
                                sessionStorage.clear();
                                self.location="../acceso/index.html";
                            },
                            id: 'btnCerrarSesion',
                            itemId: 'btnCerrarSesion',
                            width: 150,
                            iconAlign: 'right',
                            iconCls: 'exit16',
                            text: 'Cerrar Sesión',
                            textAlign: 'left'
                        }
                    ]
                }
            ],
            items: [
                {
                    xtype: 'form',
                    columnWidth: 0.1,
                    height: 140,
                    id: 'formLogoEmpresa',
                    itemId: 'formLogoEmpresa',
                    bodyCls: 'colorFormBlanco',
                    bodyPadding: 10,
                    items: [
                        {
                            xtype: 'image',
                            height: 120,
                            src: '../../../../framework/recursosIMG/LogoCopamex.png'
                        }
                    ]
                },
                {
                    xtype: 'form',
                    columnWidth: 0.9,
                    height: 140,
                    id: 'formInformacion',
                    itemId: 'formInformacion',
                    layout: 'column',
                    bodyCls: 'imagenAmbienteMenu',
                    bodyPadding: 10,
                    items: [
                        {
                            xtype: 'label',
                            columnWidth: 1,
                            cls: 'fuenteTituloGrande',
                            height: 50,
                            id: 'razonSocial',
                            itemId: 'razonSocial',
                            text: 'razonSocial'
                        },
                        {
                            xtype: 'label',
                            columnWidth: 0.5,
                            cls: 'fuenteTituloMedio',
                            id: 'nombreComercial',
                            itemId: 'nombreComercial',
                            text: 'nombreComercial'
                        },
                        {
                            xtype: 'label',
                            columnWidth: 0.5,
                            cls: 'fuenteTituloEntidad',
                            id: 'nomCompleto',
                            itemId: 'nomCompleto',
                            text: 'nomCompleto'
                        },
                        {
                            xtype: 'label',
                            columnWidth: 0.5,
                            cls: 'fuenteTituloMedio',
                            id: 'nombreSistema',
                            itemId: 'nombreSistema',
                            padding: '10 0 0 0',
                            text: 'nombreSistema'
                        },
                        {
                            xtype: 'label',
                            columnWidth: 0.5,
                            cls: 'fuenteTituloPersona',
                            id: 'nombreEntidad',
                            itemId: 'nombreEntidad',
                            padding: '10 0 0 0',
                            text: 'nombreEntidad'
                        }
                    ],
                    listeners: {
                        resize: {
                            fn: me.onFormInformacionResize,
                            scope: me
                        }
                    }
                },
                {
                    xtype: 'tabpanel',
                    columnWidth: 1,
                    id: 'tabpanelPrincipal',
                    itemId: 'tabpanelPrincipal',
                    activeTab: 0,
                    items: [
                        {
                            xtype: 'panel',
                            height: 427,
                            layout: 'column',
                            title: 'Acciones',
                            tabConfig: {
                                xtype: 'tab',
                                width: 120
                            },
                            items: [
                                {
                                    xtype: 'button',
                                    handler: function(button, e) {
                                        var winConteoProduccion = Ext.getCmp('winConteoProduccion');

                                        if(!winConteoProduccion){
                                            winConteoProduccion = new Ext.Window({
                                                title       : "ACP - Conteo de la Producción",
                                                titlebar    : false,
                                                minWidth    : 950,
                                                minWidth    : 950,
                                                minHeight   : 650,
                                                maximized   : false,
                                                maximizable : false,
                                                draggable   : false,
                                                closable    : false,
                                                modal       : true,
                                                id          : 'winConteoProduccion',
                                                itemId      : 'winConteoProduccion',
                                                layout      : 'fit',
                                                items : [{
                                                    xtype   : "component",
                                                    autoEl  : {
                                                        tag : "iframe",
                                                        src : "../conteoProduccion/index.html",
                                                        layout      : 'column'
                                                    }
                                                }],
                                                listeners:{
                                                    resize: {
                                                        fn: function(){
                                                        }
                                                    }
                                                }

                                            });
                                        }


                                        winConteoProduccionAbre();

                                        function winConteoProduccionAbre(){
                                            winConteoProduccion.show();
                                        }

                                        function winConteoProduccionCierra(){
                                            winConteoProduccion.close();
                                        }
                                    },
                                    columnWidth: 0.2,
                                    cls: 'botonGrupoNegro',
                                    height: 70,
                                    id: 'btnConteoProduccion',
                                    itemId: 'btnConteoProduccion',
                                    margin: '10 7 5 7',
                                    padding: '5 10 5 10',
                                    iconCls: 'factory-48',
                                    text: 'Conteo de<br>Producción',
                                    textAlign: 'right'
                                },
                                {
                                    xtype: 'button',
                                    handler: function(button, e) {
                                        var winConteoProduccion = Ext.getCmp('winConteoProduccion');

                                        if(!winConteoProduccion){
                                            winConteoProduccion = new Ext.Window({
                                                title       : "ACP - Conteo de la Producción",
                                                titlebar    : false,
                                                minWidth    : 950,
                                                minHeight   : 600,
                                                maximized   : true,
                                                maximizable : false,
                                                draggable   : false,
                                                closable    : false,
                                                modal       : true,
                                                id          : 'winConteoProduccion',
                                                itemId      : 'winConteoProduccion',
                                                layout      : 'fit',
                                                items : [{
                                                    xtype   : "component",
                                                    autoEl  : {
                                                        tag : "iframe",
                                                        src : "../ConteoCorrugadora/index.html",
                                                        layout      : 'fit'
                                                    }
                                                }],
                                                listeners:{
                                                    resize: {
                                                        fn: function(){
                                                        }
                                                    }
                                                }

                                            });
                                        }


                                        winConteoProduccionAbre();

                                        function winConteoProduccionAbre(){
                                            winConteoProduccion.show();
                                        }

                                        function winConteoProduccionCierra(){
                                            winConteoProduccion.close();
                                        }
                                    },
                                    columnWidth: 0.2,
                                    cls: 'botonGrupoNegro',
                                    height: 70,
                                    id: 'btnConteoProduccion1',
                                    itemId: 'btnConteoProduccion1',
                                    margin: '10 7 5 7',
                                    padding: '5 10 5 10',
                                    iconCls: 'factory-48',
                                    text: 'Conteo de<br>Corrugadora',
                                    textAlign: 'right'
                                }
                            ]
                        },
                        {
                            xtype: 'panel',
                            height: 427,
                            layout: 'column',
                            title: 'Configuración',
                            tabConfig: {
                                xtype: 'tab',
                                width: 120
                            },
                            items: [
                                {
                                    xtype: 'button',
                                    handler: function(button, e) {
                                        var winCatalogoMaquina = Ext.getCmp('winCatalogoMaquina');

                                        if(!winCatalogoMaquina){
                                            winCatalogoMaquina = new Ext.Window({
                                                title       : "ACP - Catalogo de Maquinas",
                                                titlebar    : false,
                                                minWidth    : 950,
                                                minHeight   : 600,
                                                maximized   : true,
                                                maximizable : false,
                                                draggable   : false,
                                                closable    : false,
                                                modal       : true,
                                                id          : 'winCatalogoMaquina',
                                                itemId      : 'winCatalogoMaquina',
                                                layout      : 'fit',
                                                items : [{
                                                    xtype   : "component",
                                                    autoEl  : {
                                                        tag : "iframe",
                                                        src : "../CatalogoMaquina/index.html",
                                                        layout      : 'fit'
                                                    }
                                                }],
                                                listeners:{
                                                    resize: {
                                                        fn: function(){
                                                        }
                                                    }
                                                }

                                            });
                                        }


                                        winCatalogoMaquinaAbre();

                                        function winCatalogoMaquinaAbre(){
                                            winCatalogoMaquina.show();
                                        }

                                        function winCatalogoMaquinaCierra(){
                                            winCatalogoMaquina.close();
                                        }
                                    },
                                    columnWidth: 0.2,
                                    cls: 'botonGrupoNegro',
                                    height: 70,
                                    id: 'btnCatalogoMaquina1',
                                    itemId: 'v',
                                    margin: '10 7 5 7',
                                    padding: '5 10 5 10',
                                    iconCls: 'engineering-48',
                                    text: 'Catalogo de</br>Maquinas',
                                    textAlign: 'right'
                                },
                                {
                                    xtype: 'button',
                                    handler: function(button, e) {
                                        var winCatalogoMaquina = Ext.getCmp('winCatalogoMaquina');

                                        if(!winCatalogoMaquina){
                                            winCatalogoMaquina = new Ext.Window({
                                                title       : "ACP - Catalogo de Maquinas",
                                                titlebar    : false,
                                                minWidth    : 950,
                                                minHeight   : 600,
                                                maximized   : true,
                                                maximizable : false,
                                                draggable   : false,
                                                closable    : false,
                                                modal       : true,
                                                id          : 'winCatalogoMaquina',
                                                itemId      : 'winCatalogoMaquina',
                                                layout      : 'fit',
                                                items : [{
                                                    xtype   : "component",
                                                    autoEl  : {
                                                        tag : "iframe",
                                                        src : "../CatalogoMicroboard/index.html",
                                                        layout      : 'fit'
                                                    }
                                                }],
                                                listeners:{
                                                    resize: {
                                                        fn: function(){
                                                        }
                                                    }
                                                }

                                            });
                                        }


                                        winCatalogoMaquinaAbre();

                                        function winCatalogoMaquinaAbre(){
                                            winCatalogoMaquina.show();
                                        }

                                        function winCatalogoMaquinaCierra(){
                                            winCatalogoMaquina.close();
                                        }
                                    },
                                    columnWidth: 0.2,
                                    cls: 'botonGrupoNegro',
                                    height: 70,
                                    id: 'btnCatalogoMaquina2',
                                    itemId: 'v1',
                                    margin: '10 7 5 7',
                                    padding: '5 10 5 10',
                                    iconCls: 'engineering-48',
                                    text: 'Catalogo de</br>Microboards',
                                    textAlign: 'right'
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    },

    onFormInformacionResize: function(component, width, height, oldWidth, oldHeight, eOpts) {
        var alturaForm = Ext.getCmp('windowMenuPrincipal').height - 180;
        Ext.getCmp('tabpanelPrincipal').setHeight(alturaForm);
    }

});