/*
 * File: app/model/modServices.js
 *
 * This file was generated by Sencha Architect version 3.5.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('proServices.model.modServices', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.field.Field'
    ],

    fields: [
        {
            name: 'service_id'
        },
        {
            name: 'stand_taxi'
        },
        {
            name: 'turn'
        },
        {
            name: 'car_id'
        },
        {
            name: 'date'
        },
        {
            name: 'service_type'
        },
        {
            name: 'taxi_type_fare'
        },
        {
            name: 'appointment'
        },
        {
            name: 'appointment_date'
        },
        {
            name: 'appointment_Hour'
        },
        {
            name: 'status'
        }
    ]
});