/*
 * File: app/store/storePayControl.js
 *
 * This file was generated by Sencha Architect version 3.5.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('proPayControl.store.storePayControl', {
    extend: 'Ext.data.Store',

    requires: [
        'proPayControl.model.modPayControl',
        'Ext.data.proxy.Rest'
    ],

    constructor: function (cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            storeId: 'storePayControl',
            model: 'proPayControl.model.modPayControl',
            proxy: {
                type: 'rest',
                url: ''
            },
            listeners: {
                beforeload: {
                    fn: me.onStoreBeforeLoad,
                    scope: me
                }
            }
        }, cfg)]);
    },

    onStoreBeforeLoad: function (store, operation, eOpts) {
        var storePayControl = Ext.getStore('storePayControl');
        var proxyPayControl = storePayControl.getProxy();

        var objJsonData = new Object();
        objJsonData.page = storePayControl.currentPage;
        objJsonData.start = (storePayControl.currentPage - 1) * storePayControl.pageSize;
        objJsonData.limit = storePayControl.pageSize;

        var objJsonRequest = new Object();
        objJsonRequest.apiController = 'apiPayControl';
        objJsonRequest.apiMethod = 'listPayControl';
        objJsonRequest.apiData = JSON.stringify(objJsonData);

        proxyPayControl.api.read = '../../backend/public/dataBridge/' + objJsonRequest.apiController;
        proxyPayControl.extraParams = objJsonRequest;

    }

});