/*
 * File: app/store/storeSerDetail.js
 *
 * This file was generated by Sencha Architect version 3.5.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('proPayControl.store.storeSerDetail', {
    extend: 'Ext.data.Store',

    requires: [
        'proPayControl.model.modSerDetail',
        'Ext.data.proxy.Rest',
        'Ext.data.reader.Json'
    ],

    constructor: function (cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            storeId: 'storeSerDetail',
            model: 'proPayControl.model.modSerDetail',
            proxy: {
                type: 'rest',
                url: '',
                reader: {
                    type: 'json',
                    rootProperty: 'SerDetail',
                    totalProperty: 'numService.total'
                }
            },
            listeners: {
                beforeload: {
                    fn: me.onStoreBeforeLoad,
                    scope: me
                }
            }
        }, cfg)]);
    },

    onStoreBeforeLoad: function (store, operation, eOpts) {
        var storeSerDeteil = Ext.getStore('storeSerDetail');
        var proxySerDetail = storeSerDetail.getProxy();

        var objJsonData = new Object();
        objJsonData.page = storeSerDetail.currentPage;
        objJsonData.start = (storSerDetail.currentPage - 1) * storeSerDetail.pageSize;
        objJsonData.limit = storeSerDetail.pageSize;

        var objJsonRequest = new Object();
        objJsonRequest.apiController = 'apiSerDetail';
        objJsonRequest.apiMethod = 'listSerDetail';
        objJsonRequest.apiData = JSON.stringify(objJsonData);

        proxySerDetail.api.read = '../../backend/public/dataBridge/' + objJsonRequest.apiController;
        proxySerDetail.extraParams = objJsonRequest;

    }

});