/*
 * File: app.js
 *
 * This file was generated by Sencha Architect version 3.5.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

// @require @packageOverrides
Ext.Loader.setConfig({

});


Ext.application({
    views: [
        'winAccess'
    ],
    name: 'access',

    launch: function() {
        Ext.create('access.view.winAccess', {renderTo: Ext.getBody()});
        Ext.QuickTips.init();

        appLocal = this.getApplication();
        appLocal.prepareInterface();
    },

    validateAccess: function() {
        var objJsonData = new Object();
        objJsonData.email    = trex.readElement('tfEmail');
        objJsonData.password = trex.readElement('tfPassword');

        var objJsonRequest = new Object();
        objJsonRequest.apiController = 'apiAccessLogin';
        objJsonRequest.apiMethod     = 'validateLogin';
        objJsonRequest.apiData       = JSON.stringify(objJsonData);

        var functionSuccess = function(){
            var jsonData = trex.getInfoDataBridge('apiAccessLogin');
            self.location="../workplace/index.html";
        };

        var functionFailure = function(){
            var jsonData = trex.getInfoDataBridge('apiAccessLogin');
            trex.showInfo(jsonData, 'error', 'tfEmail');
        };

        trex.doDataBridge(objJsonRequest,
                          functionSuccess,
                          null,
                          functionFailure,
                          null);
    },

    prepareInterface: function() {

        trex.translateInterface('access');
        console.log('prepare interfaz');
        return;


    }

});
