/*
 * File: app.js
 *
 * This file was generated by Sencha Architect version 3.5.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

// @require @packageOverrides
Ext.Loader.setConfig({

});


Ext.application({
    views: [
        'winAccess'
    ],
    name: 'access',

    launch: function() {
        Ext.create('access.view.winAccess', {renderTo: Ext.getBody()});
        Ext.QuickTips.init();

        var appIcon = '../../framework/terian/image/icono_itinera.ico';
        trex.changeAppIcon(appIcon);
        Ext.getDoc().dom.title = 'ItineraTMS - Access';

        appLocal = this.getApplication();
        appLocal.prepareInterface();
    },

    validateAccess: function() {
        var objJsonData = new Object();
        objJsonData.email    = trex.readElement('tfEmail');
        objJsonData.password = trex.readElement('tfPassword');

        var objJsonRequest = new Object();
        objJsonRequest.apiController = 'apiAccessLogin';
        objJsonRequest.apiMethod     = 'validateLogin';
        objJsonRequest.apiData       = JSON.stringify(objJsonData);

        var functionSuccess = function(){
            var jsonData = trex.getInfoDataBridge('apiAccessLogin');
            console.log(jsonData);

            var objSession = new Object();
            objSession.company_code = jsonData.sessionData.company_code;
            objSession.company_name = jsonData.sessionData.company_name;
            objSession.user_id = jsonData.sessionData.user_id;
            objSession.user_name = jsonData.sessionData.user_name;
            objSession.user_profile = jsonData.sessionData.user_profile;
            objSession.user_email = jsonData.sessionData.user_email;
            objSession.profile_code = jsonData.sessionData.profile_code;
            objSession.system_code = jsonData.sessionData.system_code;
            objSession.system_name = jsonData.sessionData.system_name;
            objSession.system_version = jsonData.sessionData.system_version;

            trex.generateSession(objSession);
            self.location="../workplace/index.html";
        };

        var functionFailure = function(){
            var jsonData = trex.getInfoDataBridge('apiAccessLogin');
            trex.showInfo(jsonData, 'error', 'tfEmail');
        };

        trex.doDataBridge(objJsonRequest,
                          functionSuccess,
                          null,
                          functionFailure,
                          null);
    },

    prepareInterface: function() {

        trex.translateInterface('access');
        console.log('prepare interfaz');
        return;


    }

});
