/*
 * File: app/view/formMaintenance.js
 * Date: Wed Apr 27 2016 17:33:18 GMT-0500 (CDT)
 *
 * This file was generated by Sencha Architect version 3.5.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('catCustomer.view.formMaintenance', {
    extend: 'Ext.form.Panel',
    alias: 'widget.formMaintenance',

    requires: [
        'catCustomer.view.formMaintenanceViewModel',
        'Ext.button.Button',
        'Ext.toolbar.Separator',
        'Ext.toolbar.Fill',
        'Ext.grid.Panel',
        'Ext.view.Table',
        'Ext.grid.column.Column',
        'Ext.toolbar.Paging'
    ],

    viewModel: {
        type: 'formmaintenance'
    },
    id: 'formMaintenance',
    itemId: 'formMaintenance',
    layout: 'column',
    bodyPadding: 10,
    manageHeight: false,
    defaultListenerScope: true,

    dockedItems: [
        {
            xtype: 'toolbar',
            dock: 'top',
            id: 'toolbarMaintenance',
            itemId: 'toolbarMaintenance',
            items: [
                {
                    xtype: 'button',
                    handler: function(button, e) {
                        Ext.getCmp('formMaintenance').showCustomer();
                    },
                    id: 'btnView',
                    itemId: 'btnView',
                    width: 120,
                    iconCls: 'ion-eye icon16',
                    text: 'View',
                    textAlign: 'left'
                },
                {
                    xtype: 'button',
                    handler: function(button, e) {
                        var winCustomer = Ext.getCmp('winCustomer');

                        if(!winCustomer){
                            winCustomer = Ext.create('widget.winCustomer');
                            winCustomer.show();
                            trex.hideScrollBars();
                        }
                    },
                    id: 'btnCreate',
                    itemId: 'btnCreate',
                    width: 120,
                    iconCls: 'ion-plus-circled icon16',
                    text: 'Create',
                    textAlign: 'left'
                },
                {
                    xtype: 'button',
                    handler: function(button, e) {
                        Ext.getCmp('formMaintenance').showCustomer('edit');
                    },
                    id: 'btnUpdate',
                    itemId: 'btnUpdate',
                    width: 120,
                    iconCls: 'ion-edit icon16',
                    text: 'Update',
                    textAlign: 'left'
                },
                {
                    xtype: 'button',
                    handler: function(button, e) {
                        var msgFunction = function(){
                            Ext.getCmp('formMaintenance').deleteCustomer();

                        };

                        var msgType = 'question';
                        var msgTitle = 'Delete Customer';
                        var msgContent = 'Do you want to delete the Customer record: ';

                        trex.message(msgType,
                        msgTitle,
                        msgContent,
                        msgFunction);

                        return;
                    },
                    id: 'btnDelete',
                    itemId: 'btnDelete',
                    width: 120,
                    iconCls: 'ion-trash-a icon16',
                    text: 'Delete',
                    textAlign: 'left'
                },
                {
                    xtype: 'tbseparator',
                    width: 30
                },
                {
                    xtype: 'button',
                    id: 'btnFind',
                    itemId: 'btnFind',
                    width: 120,
                    iconCls: 'ion-ios-search-strong icon16',
                    text: 'Find',
                    textAlign: 'left'
                },
                {
                    xtype: 'button',
                    id: 'btnFilter',
                    itemId: 'btnFilter',
                    width: 120,
                    iconCls: 'ion-funnel icon16',
                    text: 'Filter',
                    textAlign: 'left'
                },
                {
                    xtype: 'tbseparator',
                    width: 30
                },
                {
                    xtype: 'tbfill'
                },
                {
                    xtype: 'button',
                    id: 'btnInformation',
                    itemId: 'btnInformation',
                    width: 120,
                    iconCls: 'ion-information-circled icon16',
                    text: 'Information',
                    textAlign: 'left'
                },
                {
                    xtype: 'button',
                    handler: function(button, e) {
                        var win = window.parent.Ext.getCmp('catCustomer');
                        if(win)win[win.closeAction]();
                    },
                    id: 'btnExit',
                    itemId: 'btnExit',
                    width: 120,
                    iconCls: 'ion-android-exit icon16',
                    text: 'Exit',
                    textAlign: 'left'
                }
            ]
        }
    ],
    items: [
        {
            xtype: 'gridpanel',
            columnWidth: 1,
            height: 350,
            id: 'gridCustomers',
            itemId: 'gridCustomers',
            maxHeight: 350,
            title: 'Customers',
            forceFit: true,
            store: 'storeCustomer',
            viewConfig: {
                height: 220,
                maxWidth: 1390
            },
            columns: [
                {
                    xtype: 'gridcolumn',
                    id: 'customer_num',
                    itemId: 'customer_num',
                    minWidth: 110,
                    dataIndex: 'customer_num',
                    text: 'Cust </br> Number'
                },
                {
                    xtype: 'gridcolumn',
                    id: 'short_name',
                    itemId: 'short_name',
                    width: 160,
                    dataIndex: 'short_name',
                    text: 'Short Name'
                },
                {
                    xtype: 'gridcolumn',
                    id: 'company_name',
                    itemId: 'company_name',
                    width: 250,
                    dataIndex: 'company_name',
                    text: 'Company Name'
                },
                {
                    xtype: 'gridcolumn',
                    id: 'tax_id',
                    itemId: 'tax_id',
                    width: 180,
                    dataIndex: 'tax_id',
                    text: 'Tax Id'
                },
                {
                    xtype: 'gridcolumn',
                    id: 'address',
                    itemId: 'address',
                    width: 250,
                    dataIndex: 'address',
                    text: 'Address'
                },
                {
                    xtype: 'gridcolumn',
                    id: 'country',
                    itemId: 'country',
                    minWidth: 110,
                    dataIndex: 'country',
                    text: 'Country'
                },
                {
                    xtype: 'gridcolumn',
                    id: 'city',
                    itemId: 'city',
                    minWidth: 110,
                    dataIndex: 'city',
                    text: 'City'
                },
                {
                    xtype: 'gridcolumn',
                    id: 'region',
                    itemId: 'region',
                    minWidth: 110,
                    dataIndex: 'regiion',
                    text: 'Region'
                },
                {
                    xtype: 'gridcolumn',
                    id: 'location',
                    itemId: 'location',
                    minWidth: 110,
                    dataIndex: 'location',
                    text: 'Location'
                },
                {
                    xtype: 'gridcolumn',
                    id: 'postal_code',
                    itemId: 'postal_code',
                    dataIndex: 'postal_code',
                    text: 'Postal Code'
                },
                {
                    xtype: 'gridcolumn',
                    id: 'phone',
                    itemId: 'phone',
                    dataIndex: 'phone',
                    text: 'Phone'
                },
                {
                    xtype: 'gridcolumn',
                    id: 'contact_name',
                    itemId: 'contact_name',
                    dataIndex: 'contact_name',
                    text: 'Contact Name'
                },
                {
                    xtype: 'gridcolumn',
                    id: 'contact_phone',
                    itemId: 'contact_phone',
                    dataIndex: 'contact_phone',
                    text: 'Contact Phone'
                },
                {
                    xtype: 'gridcolumn',
                    id: 'email',
                    itemId: 'email',
                    dataIndex: 'email',
                    text: 'Email'
                },
                {
                    xtype: 'gridcolumn',
                    id: 'website',
                    itemId: 'website',
                    dataIndex: 'website',
                    text: 'Website'
                },
                {
                    xtype: 'gridcolumn',
                    id: 'isactive',
                    itemId: 'isactive',
                    dataIndex: 'isactive',
                    text: 'Active'
                },
                {
                    xtype: 'gridcolumn',
                    id: 'created_date',
                    itemId: 'created_date',
                    dataIndex: 'create_date',
                    text: 'Created </br> Date'
                },
                {
                    xtype: 'gridcolumn',
                    id: 'stand_taxi',
                    itemId: 'stand_taxi',
                    dataIndex: 'stand_taxi',
                    text: 'Stand </br> Taxi'
                },
                {
                    xtype: 'gridcolumn',
                    id: 'sector',
                    itemId: 'sector',
                    dataIndex: 'sector',
                    text: 'Sector'
                }
            ],
            dockedItems: [
                {
                    xtype: 'pagingtoolbar',
                    dock: 'bottom',
                    height: 26,
                    id: 'pagingToolbar',
                    itemId: 'pagingToolbar',
                    width: 360,
                    displayInfo: true,
                    store: 'storeCustomer'
                }
            ],
            listeners: {
                itemdblclick: 'onGridCustomersItemDblClick',
                itemclick: 'onGridCustomersItemClick'
            }
        },
        {
            xtype: 'gridpanel',
            columnWidth: 1,
            id: 'gridCustAddress',
            itemId: 'gridCustAddress',
            margin: '5 0 0 0',
            title: 'Customers Address',
            enableColumnHide: false,
            forceFit: true,
            store: 'storeCustAddress',
            viewConfig: {
                height: 220
            },
            columns: [
                {
                    xtype: 'gridcolumn',
                    id: 'branch_office',
                    itemId: 'branch_office',
                    width: 180,
                    dataIndex: 'branch_office',
                    text: 'Branch </br> Office'
                },
                {
                    xtype: 'gridcolumn',
                    id: 'contact_name1',
                    itemId: 'contact_name',
                    dataIndex: 'contact_name',
                    text: 'Contact Name'
                },
                {
                    xtype: 'gridcolumn',
                    id: 'contact_phone1',
                    itemId: 'contact_phone',
                    dataIndex: 'contact_phone',
                    text: 'Contact Phone'
                },
                {
                    xtype: 'gridcolumn',
                    id: 'address1',
                    itemId: 'address',
                    width: 250,
                    dataIndex: 'address',
                    text: 'Address'
                },
                {
                    xtype: 'gridcolumn',
                    id: 'country1',
                    itemId: 'country',
                    dataIndex: 'country',
                    text: 'Country'
                },
                {
                    xtype: 'gridcolumn',
                    id: 'city1',
                    itemId: 'city',
                    dataIndex: 'city',
                    text: 'City'
                },
                {
                    xtype: 'gridcolumn',
                    id: 'region1',
                    itemId: 'region',
                    dataIndex: 'regiion',
                    text: 'Region'
                },
                {
                    xtype: 'gridcolumn',
                    id: 'location1',
                    itemId: 'location',
                    dataIndex: 'location',
                    text: 'Location'
                },
                {
                    xtype: 'gridcolumn',
                    id: 'postal_code1',
                    itemId: 'postal_code',
                    dataIndex: 'postal_code',
                    text: 'Postal Code'
                },
                {
                    xtype: 'gridcolumn',
                    id: 'phone1',
                    itemId: 'phone',
                    dataIndex: 'phone',
                    text: 'Phone'
                },
                {
                    xtype: 'gridcolumn',
                    id: 'email1',
                    itemId: 'email',
                    dataIndex: 'email',
                    text: 'Email'
                },
                {
                    xtype: 'gridcolumn',
                    id: 'isactive1',
                    itemId: 'isactive',
                    dataIndex: 'isactive',
                    text: 'Active'
                },
                {
                    xtype: 'gridcolumn',
                    id: 'created_date1',
                    itemId: 'created_date',
                    dataIndex: 'create_date',
                    text: 'Created </br> Date'
                },
                {
                    xtype: 'gridcolumn',
                    id: 'stand_taxi1',
                    itemId: 'stand_taxi',
                    dataIndex: 'stand_taxi',
                    text: 'Stand </br> Taxi'
                },
                {
                    xtype: 'gridcolumn',
                    id: 'sector1',
                    itemId: 'sector',
                    dataIndex: 'sector',
                    text: 'Sector'
                }
            ],
            dockedItems: [
                {
                    xtype: 'pagingtoolbar',
                    dock: 'bottom',
                    height: 26,
                    id: 'pagingToolbar1',
                    itemId: 'pagingToolbar',
                    width: 360,
                    displayInfo: true,
                    store: 'storeCustAddress',
                    items: [
                        {
                            xtype: 'tbseparator',
                            width: 50
                        },
                        {
                            xtype: 'button',
                            id: 'btnCreateCustomerAddress',
                            itemId: 'btnCreateCustomerAddress',
                            width: 40,
                            iconCls: 'ion-ios-compose icon16',
                            listeners: {
                                click: 'onBtnCreateCustomerAddressClick'
                            }
                        },
                        {
                            xtype: 'button',
                            handler: function (button, e) {

                            },
                            id: 'btnUpdateCustomerAddress',
                            itemId: 'btnUpdateCustomerAddress',
                            width: 40,
                            iconCls: 'ion-edit icon16'
                        },
                        {
                            xtype: 'button',
                            handler: function (button, e) {

                            },
                            id: 'btnDeleteCustomerAddress',
                            itemId: 'btnDeleteCustomerAddress',
                            width: 40,
                            iconCls: 'ion-android-delete icon16'
                        },
                        {
                            xtype: 'tbseparator',
                            width: 50
                        },
                        {
                            xtype: 'button',
                            handler: function (button, e) {

                            },
                            id: 'btnAddClient',
                            itemId: 'btnAddClient',
                            width: 40,
                            iconCls: 'ion-person-stalker icon16'
                        }
                    ]
                }
            ],
            listeners: {
                itemdblclick: 'onGridCustAddressItemDblClick',
                itemclick: 'onGridCustAddressItemClick'
            }
        }
    ],

    onGridCustomersItemDblClick: function(dataview, record, item, index, e, eOpts) {
        Ext.getCmp('formMaintenance').showCustomer();
    },

    onGridCustomersItemClick: function(dataview, record, item, index, e, eOpts) {
        Ext.getCmp('formMaintenance').CustomerID = record.data.id;
        Ext.getCmp('formMaintenance').CustomerRecord = record.data;
    },

    onBtnCreateCustomerAddressClick: function (button, e, eOpts) {
        trex.showWindow('winCustAddress');
    },

    onGridCustAddressItemDblClick: function (dataview, record, item, index, e, eOpts) {
        Ext.getCmp('formMaintenance').showCustomer();
    },

    onGridCustAddressItemClick: function (dataview, record, item, index, e, eOpts) {
        Ext.getCmp('formMaintenance').CustomerID = record.data.id;
        Ext.getCmp('formMaintenance').CustomerRecord = record.data;
    },

    showCustomer: function(pMode) {
        var apiController = 'apiCustomer';
        var apiMethod     = 'showCustomer';
        var objJsonData = new Object();
        objJsonData.CustomerID    = Ext.getCmp('formMaintenance').CustomerID;

        var objJsonRequest = new Object();
        objJsonRequest.apiController = apiController;
        objJsonRequest.apiMethod     = apiMethod;
        objJsonRequest.apiData       = JSON.stringify(objJsonData);

        var functionSuccess = function(){
            var jsonData = trex.getInfoDataBridge(apiController);


            var winCustomer = Ext.getCmp('winCustomer');

            if(!winCustomer){
                winCustomer = Ext.create('widget.winCustomer');
                winCustomer.show();
                trex.hideScrollBars();
            }

            trex.showRecord(jsonData,'customers');

        };

        var functionFailure = function(){
            var jsonData = trex.getInfoDataBridge(apiController);
        };

        trex.doDataBridge(objJsonRequest,
                          functionSuccess,
                          null,
                          functionFailure,
                          null);


    },

    deleteCustomer: function() {
        alert('regisdtro borrado');

        var formRecord    = 'formCustomer';
        var apiController = 'apiCustomer';
        var apiMethod     = 'deleteCustomer';

        var objJsonData = new Object();
        objJsonData.customerId    = Ext.getCmp('formMaintenance').CustomerRecord.id;

        var objJsonRequest = new Object();
        objJsonRequest.apiController = apiController;
        objJsonRequest.apiMethod     = apiMethod;
        objJsonRequest.apiData       = JSON.stringify(objJsonData);

        var functionSuccess = function(){
            var jsonData = trex.getInfoDataBridge(apiController);

            console.log(jsonData);
            trex.showInfo(jsonData, 'info');

        };

        var functionFailure = function(){
            var jsonData = trex.getInfoDataBridge(apiController);
            trex.showInfo(jsonData, 'error', 'tfCompany');
        };

        trex.doDataBridge(objJsonRequest,
                          functionSuccess,
                          null,
                          functionFailure,
                          null);
    }

});