/*
 * File: app/view/winCustomer.js
 * Date: Sun May 01 2016 11:27:16 GMT-0500 (CDT)
 *
 * This file was generated by Sencha Architect version 3.5.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('catCustomer.view.winCustomer', {
    extend: 'Ext.window.Window',
    alias: 'widget.winCustomer',

    requires: [
        'catCustomer.view.winCustomerViewModel',
        'Ext.form.Panel',
        'Ext.form.FieldSet',
        'Ext.toolbar.Spacer',
        'Ext.form.field.Date',
        'Ext.form.field.Checkbox',
        'Ext.button.Button',
        'Ext.toolbar.Toolbar',
        'Ext.toolbar.Fill'
    ],

    viewModel: {
        type: 'wincustomer'
    },
    height: 610,
    id: 'winCustomer',
    itemId: 'winCustomer',
    minHeight: 610,
    minWidth: 1000,
    width: 1000,
    layout: 'column',
    closable: false,
    title: 'Customer',
    modal: true,
    defaultListenerScope: true,

    items: [
        {
            xtype: 'form',
            confirmRecord: function() {
                if(Ext.getCmp('formCustomer').isValid()){
                    var formRecord    = 'formCustomer';
                    var apiController = 'apiCustomer';
                    var apiMethod     = 'createCustomer';

                    var objJsonRequest = new Object();
                    objJsonRequest.apiController = apiController;
                    objJsonRequest.apiMethod     = apiMethod;
                    objJsonRequest.apiData       = trex.prepareFormFields(formRecord);

                    var functionSuccess = function(){
                        var jsonData = trex.getInfoDataBridge(apiController);

                        trex.showInfo(jsonData, 'information');

                        var winCustomer = Ext.getCmp('winCustomer');
                        winCustomer.close();

                        Ext.getStore('storeCustomer').load();

                    };

                    var functionFailure = function(){
                        var jsonData = trex.getInfoDataBridge(apiController);
                        trex.showInfo(jsonData, 'error', 'tfCompany');
                    };

                    trex.doDataBridge(objJsonRequest,
                    functionSuccess,
                    null,
                    functionFailure,
                    null);

                }
                else{

                    trex.message('error',
                    'Incomplete Form',
                    'You must fill the required fields');
                }
            },
            columnWidth: 1,
            id: 'formCustomer',
            itemId: 'formCustomer',
            layout: 'column',
            bodyPadding: 10,
            items: [
                {
                    xtype: 'fieldset',
                    columnWidth: 1,
                    id: 'fieldsetCustomerInformation',
                    itemId: 'fieldsetCustomerInformation',
                    layout: 'column',
                    title: '<b>General information</b>',
                    items: [
                        {
                            xtype: 'textfield',
                            columnWidth: 0.33,
                            disabledCls: 'disabledField',
                            id: 'tfShortName',
                            itemId: 'tfShortName',
                            margin: '0 5 5 5',
                            fieldLabel: 'Short Name',
                            labelClsExtra: 'requiredField',
                            labelWidth: 90,
                            allowBlank: false
                        },
                        {
                            xtype: 'textfield',
                            columnWidth: 0.66,
                            disabledCls: 'disabledField',
                            id: 'tfCompany',
                            itemId: 'tfCompany',
                            margin: '0 5 5 5',
                            fieldLabel: 'Company',
                            labelClsExtra: 'requiredField',
                            labelWidth: 90,
                            allowBlank: false
                        },
                        {
                            xtype: 'textfield',
                            columnWidth: 0.33,
                            disabledCls: 'disabledField',
                            id: 'tfTaxId',
                            itemId: 'tfTaxId',
                            margin: '0 5 5 5',
                            fieldLabel: 'Tax ID',
                            labelClsExtra: 'requiredField',
                            labelWidth: 90,
                            allowBlank: false
                        },
                        {
                            xtype: 'textfield',
                            columnWidth: 0.33,
                            disabledCls: 'disabledField',
                            id: 'tfEmail',
                            itemId: 'tfEmail',
                            margin: '0 5 5 5',
                            fieldLabel: 'Email',
                            labelClsExtra: 'requiredField',
                            labelWidth: 90,
                            allowBlank: false
                        },
                        {
                            xtype: 'tbspacer',
                            columnWidth: 1
                        },
                        {
                            xtype: 'textfield',
                            columnWidth: 0.33,
                            disabledCls: 'disabledField',
                            id: 'tfPassword',
                            itemId: 'tfPassword',
                            margin: '0 5 5 5',
                            fieldLabel: 'Password',
                            labelWidth: 90,
                            inputType: 'password'
                        },
                        {
                            xtype: 'datefield',
                            columnWidth: 0.3,
                            disabledCls: 'disabledField',
                            id: 'dtCreatedAt',
                            itemId: 'dtCreatedAt',
                            margin: '0 5 5 5',
                            fieldLabel: 'Created',
                            labelWidth: 90
                        },
                        {
                            xtype: 'checkboxfield',
                            columnWidth: 0.2,
                            disabledCls: 'disabledField',
                            id: 'chActive',
                            itemId: 'chActive',
                            margin: '0 5 5 5',
                            boxLabel: 'Active'
                        },
                        {
                            xtype: 'tbspacer',
                            columnWidth: 1
                        },
                        {
                            xtype: 'textfield',
                            columnWidth: 0.33,
                            disabledCls: 'disabledField',
                            id: 'tfPhone',
                            itemId: 'tfPhone',
                            margin: '0 5 5 5',
                            fieldLabel: 'Phone',
                            labelClsExtra: 'requiredField',
                            labelWidth: 90,
                            allowBlank: false
                        },
                        {
                            xtype: 'textfield',
                            columnWidth: 0.5,
                            disabledCls: 'disabledField',
                            id: 'tfWebsite',
                            itemId: 'tfWebsite',
                            margin: '0 5 5 5',
                            fieldLabel: 'WebSite',
                            labelWidth: 90
                        }
                    ]
                },
                {
                    xtype: 'fieldset',
                    columnWidth: 1,
                    height: 160,
                    id: 'fieldsetAddress',
                    itemId: 'fieldsetAddress',
                    layout: 'column',
                    title: '<b>Address</b>',
                    items: [
                        {
                            xtype: 'textfield',
                            columnWidth: 0.7,
                            disabledCls: 'disabledField',
                            id: 'tfAddress',
                            itemId: 'tfAddress',
                            margin: '0 5 5 5',
                            maxWidth: 665,
                            minWidth: 665,
                            width: 665,
                            fieldLabel: 'Address',
                            labelClsExtra: 'requiredField',
                            labelWidth: 90,
                            allowBlank: false
                        },
                        {
                            xtype: 'textfield',
                            columnWidth: 0.2,
                            disabledCls: 'disabledField',
                            id: 'tfZipCode',
                            itemId: 'tfZipCode',
                            margin: '0 5 5 5',
                            fieldLabel: 'Zip Code',
                            labelClsExtra: 'requiredField',
                            labelWidth: 90,
                            allowBlank: false
                        },
                        {
                            xtype: 'tbspacer',
                            columnWidth: 1
                        },
                        {
                            xtype: 'textfield',
                            columnWidth: 0.3,
                            disabledCls: 'disabledField',
                            id: 'tfCountry',
                            itemId: 'tfCountry',
                            margin: '0 5 5 5',
                            maxWidth: 180,
                            width: 180,
                            fieldLabel: 'Country',
                            labelClsExtra: 'requiredField',
                            labelWidth: 90,
                            allowBlank: false,
                            listeners: {
                                blur: 'onTfCountryBlur'
                            }
                        },
                        {
                            xtype: 'button',
                            columnWidth: 0.1,
                            id: 'btnSearchCountry',
                            itemId: 'btnSearchCountry',
                            maxWidth: 30,
                            width: 30,
                            iconCls: 'ion-search icon16',
                            listeners: {
                                click: 'onBtnSearchCountryClick'
                            }
                        },
                        {
                            xtype: 'textfield',
                            columnWidth: 0.5,
                            id: 'tfCountryName',
                            itemId: 'tfCountryName',
                            maxWidth: 450,
                            width: 450
                        },
                        {
                            xtype: 'tbspacer',
                            columnWidth: 1,
                            id: 'spacerAddress1'
                        },
                        {
                            xtype: 'textfield',
                            columnWidth: 0.3,
                            disabledCls: 'disabledField',
                            id: 'tfState',
                            itemId: 'tfState',
                            margin: '0 5 5 5',
                            maxWidth: 180,
                            width: 180,
                            fieldLabel: 'State',
                            labelClsExtra: 'requiredField',
                            labelWidth: 90,
                            allowBlank: false,
                            listeners: {
                                blur: 'onTfCountryBlur1'
                            }
                        },
                        {
                            xtype: 'button',
                            columnWidth: 0.1,
                            id: 'btnSearchState',
                            itemId: 'btnSearchState',
                            maxWidth: 30,
                            width: 30,
                            iconCls: 'ion-search icon16',
                            listeners: {
                                click: 'onBtnSearchCountryClick1'
                            }
                        },
                        {
                            xtype: 'textfield',
                            columnWidth: 0.5,
                            id: 'tfStateName',
                            itemId: 'tfStateName',
                            maxWidth: 450,
                            width: 450
                        },
                        {
                            xtype: 'tbspacer',
                            columnWidth: 1,
                            id: 'spacerAddress2'
                        },
                        {
                            xtype: 'textfield',
                            columnWidth: 0.3,
                            disabledCls: 'disabledField',
                            id: 'tfCity',
                            itemId: 'tfCity',
                            margin: '0 5 5 5',
                            maxWidth: 180,
                            width: 180,
                            fieldLabel: 'City',
                            labelClsExtra: 'requiredField',
                            labelWidth: 90,
                            allowBlank: false,
                            listeners: {
                                blur: 'onTfCityBlur'
                            }
                        },
                        {
                            xtype: 'button',
                            columnWidth: 0.1,
                            id: 'btnSearchCity',
                            itemId: 'btnSearchCity',
                            maxWidth: 30,
                            width: 30,
                            iconCls: 'ion-search icon16',
                            listeners: {
                                click: 'onBtnSearchCityClick'
                            }
                        },
                        {
                            xtype: 'textfield',
                            columnWidth: 0.75,
                            id: 'tfCityName',
                            itemId: 'tfCityName',
                            maxWidth: 450,
                            width: 450
                        },
                        {
                            xtype: 'tbspacer',
                            columnWidth: 1
                        },
                        {
                            xtype: 'textfield',
                            columnWidth: 0.3,
                            disabledCls: 'disabledField',
                            id: 'tfRegion',
                            itemId: 'tfRegion',
                            margin: '0 5 5 5',
                            maxWidth: 180,
                            width: 180,
                            fieldLabel: 'Region',
                            labelClsExtra: 'requiredField',
                            labelWidth: 90,
                            allowBlank: false,
                            listeners: {
                                blur: 'onTfRegionBlur'
                            }
                        },
                        {
                            xtype: 'button',
                            columnWidth: 0.1,
                            maxWidth: 30,
                            width: 30,
                            iconCls: 'ion-search icon16',
                            listeners: {
                                click: 'onButtonClick'
                            }
                        },
                        {
                            xtype: 'textfield',
                            columnWidth: 0.75,
                            id: 'tfRegionName',
                            itemId: 'tfRegionName',
                            maxWidth: 450,
                            width: 450
                        },
                        {
                            xtype: 'tbspacer',
                            columnWidth: 1
                        }
                    ]
                },
                {
                    xtype: 'fieldset',
                    columnWidth: 1,
                    id: 'fieldsetService',
                    itemId: 'fieldsetService',
                    layout: 'column',
                    title: '<b>Service</b>',
                    items: [
                        {
                            xtype: 'textfield',
                            columnWidth: 0.3,
                            disabledCls: 'disabledField',
                            id: 'tfStandTaxi',
                            itemId: 'tfStandTaxi',
                            margin: '0 5 5 5',
                            maxWidth: 180,
                            width: 180,
                            fieldLabel: 'Stand Taxi',
                            labelClsExtra: 'requiredField',
                            labelWidth: 90,
                            allowBlank: false
                        },
                        {
                            xtype: 'button',
                            columnWidth: 0.1,
                            id: 'btnSearchCountry1',
                            itemId: 'btnSearchCountry1',
                            maxWidth: 30,
                            width: 30,
                            iconCls: 'ion-search icon16'
                        },
                        {
                            xtype: 'textfield',
                            columnWidth: 0.75,
                            id: 'tfCountryName1',
                            itemId: 'tfCountryName1',
                            maxWidth: 450,
                            width: 450
                        },
                        {
                            xtype: 'tbspacer',
                            columnWidth: 1
                        },
                        {
                            xtype: 'textfield',
                            columnWidth: 0.3,
                            disabledCls: 'disabledField',
                            id: 'tfSector',
                            itemId: 'tfSector',
                            margin: '0 5 5 5',
                            maxWidth: 180,
                            width: 180,
                            fieldLabel: 'Sector',
                            labelClsExtra: 'requiredField',
                            labelWidth: 90,
                            allowBlank: false
                        },
                        {
                            xtype: 'button',
                            columnWidth: 0.1,
                            id: 'btnSearchCountry2',
                            itemId: 'btnSearchCountry2',
                            maxWidth: 30,
                            width: 30,
                            iconCls: 'ion-search icon16'
                        },
                        {
                            xtype: 'textfield',
                            columnWidth: 0.75,
                            id: 'tfCountryName2',
                            itemId: 'tfCountryName2',
                            maxWidth: 450,
                            width: 450
                        }
                    ]
                },
                {
                    xtype: 'fieldset',
                    columnWidth: 1,
                    id: 'fieldsetContact',
                    itemId: 'fieldsetContact',
                    layout: 'column',
                    title: '<b>Contact</b>',
                    items: [
                        {
                            xtype: 'textfield',
                            columnWidth: 0.5,
                            disabledCls: 'disabledField',
                            id: 'tfContactName',
                            itemId: 'tfContactName',
                            margin: '0 5 5 5',
                            fieldLabel: 'Contact Name',
                            labelClsExtra: 'requiredField',
                            labelWidth: 90,
                            allowBlank: false
                        },
                        {
                            xtype: 'textfield',
                            columnWidth: 0.5,
                            disabledCls: 'disabledField',
                            id: 'tfContactPhone',
                            itemId: 'tfContactPhone',
                            margin: '0 5 5 5',
                            fieldLabel: 'Contact Phone',
                            labelClsExtra: 'requiredField',
                            labelWidth: 90,
                            allowBlank: false
                        }
                    ]
                },
                {
                    xtype: 'fieldset',
                    columnWidth: 1,
                    id: 'fieldsetGeolocalization',
                    itemId: 'fieldsetGeolocalization',
                    layout: 'column',
                    title: '<b>Geolocalization</b>',
                    items: [
                        {
                            xtype: 'textfield',
                            columnWidth: 0.5,
                            disabledCls: 'disabledField',
                            id: 'tfLatitude',
                            itemId: 'tfLatitude',
                            margin: '0 5 5 5',
                            fieldLabel: 'Latitude',
                            labelClsExtra: '',
                            labelWidth: 90
                        },
                        {
                            xtype: 'textfield',
                            columnWidth: 0.5,
                            disabledCls: 'disabledField',
                            id: 'tfLongitude',
                            itemId: 'tfLongitude',
                            margin: '0 5 5 5',
                            fieldLabel: 'Longitude',
                            labelClsExtra: '',
                            labelWidth: 90
                        },
                        {
                            xtype: 'textfield',
                            columnWidth: 1,
                            disabledCls: 'disabledField',
                            id: 'tfGeocodeUrl',
                            itemId: 'tfGeocodeUrl',
                            margin: '0 5 5 5',
                            fieldLabel: 'Geocode URL',
                            labelWidth: 90
                        }
                    ]
                }
            ]
        }
    ],
    dockedItems: [
        {
            xtype: 'toolbar',
            dock: 'top',
            id: 'toolbarCustomer',
            itemId: 'toolbarCustomer',
            items: [
                {
                    xtype: 'button',
                    handler: function(button, e) {
                        Ext.getCmp('formCustomer').confirmRecord();
                    },
                    id: 'btnConfirmCustomer',
                    itemId: 'btnConfirmCustomer',
                    width: 120,
                    iconCls: 'ion-checkmark-circled icon16',
                    text: 'Confirm',
                    textAlign: 'left'
                },
                {
                    xtype: 'tbfill',
                    id: 'filCustomer',
                    itemId: 'filCustomer'
                },
                {
                    xtype: 'button',
                    handler: function(button, e) {
                        var winCustomer = Ext.getCmp('winCustomer');
                        winCustomer.close();
                    },
                    id: 'btnCloseCustomer',
                    itemId: 'btnCloseCustomer',
                    width: 120,
                    iconCls: 'ion-close-circled icon16',
                    text: 'Close',
                    textAlign: 'left'
                }
            ]
        }
    ],

    onTfCountryBlur: function (component, event, eOpts) {
        if (trex.readElement('tfCountry') === '') {
            return;
        }

        var functionSuccess = function () {
            var jsonData = trex.getInfoDataBridge('apiCountry');
            console.log('pais valido');
            console.log(jsonData);

            trex.writeElement('tfCountry', jsonData.country[0].country_code);
            trex.writeElement('tfCountryName', jsonData.country[0].country_name);
        };

        var functionFailure = function () {
            var jsonData = trex.getInfoDataBridge('apiCountry');
            trex.showInfo(jsonData, 'error', 'tfCountry');
        };

        var objJsonData = new Object();
        objJsonData.countryCode = trex.readElement('tfCountry');

        var objJsonRequest = new Object();
        objJsonRequest.apiController = 'apiCountry';
        objJsonRequest.apiMethod = 'validateCountry';
        objJsonRequest.apiData = JSON.stringify(objJsonData);

        trex.doDataBridge(objJsonRequest,
            functionSuccess,
            null,
            functionFailure,
            null);
    },

    onBtnSearchCountryClick: function (button, e, eOpts) {

        trex.showWindow('winCountrySearch');
        trex.refreshGrid('gridCountry');

    },

    onTfCountryBlur1: function (component, event, eOpts) {
        if (trex.readElement('tfState') === '') {
            return;
        }

        var functionSuccess = function () {
            var jsonData = trex.getInfoDataBridge('apiState');
            console.log('pais valido');
            console.log(jsonData);

            trex.writeElement('tfState', jsonData.country[0].country_code);
            trex.writeElement('tfStateName', jsonData.country[0].country_name);
        };

        var functionFailure = function () {
            var jsonData = trex.getInfoDataBridge('apiState');
            trex.showInfo(jsonData, 'error', 'tfState');
        };

        var objJsonData = new Object();
        objJsonData.countryCode = trex.readElement('tfState');

        var objJsonRequest = new Object();
        objJsonRequest.apiController = 'apiState';
        objJsonRequest.apiMethod = 'validateState';
        objJsonRequest.apiData = JSON.stringify(objJsonData);

        trex.doDataBridge(objJsonRequest,
            functionSuccess,
            null,
            functionFailure,
            null);
    },

    onBtnSearchCountryClick1: function (button, e, eOpts) {

        trex.showWindow('winStateSearch');
        trex.refreshGrid('gridState');

    },

    onTfCityBlur: function (component, event, eOpts) {

    },

    onBtnSearchCityClick: function (button, e, eOpts) {
        trex.showWindow('winCitySearch');
        trex.refreshGrid('gridCity');
    },

    onTfRegionBlur: function (component, event, eOpts) {
        if (trex.readElement('tfRegion') === '') {
            return;
        }

        var functionSuccess = function () {
            var jsonData = trex.getInfoDataBridge('apiState');
            console.log('region valido');
            console.log(jsonData);

            trex.writeElement('tfRegion', jsonData.country[0].region_code);
            trex.writeElement('tfRegionName', jsonData.country[0].region_name);
        };

        var functionFailure = function () {
            var jsonData = trex.getInfoDataBridge('apiState');
            trex.showInfo(jsonData, 'error', 'tfState');
        };

        var objJsonData = new Object();
        objJsonData.countryCode = trex.readElement('tfCountry');
        objJsonData.stateCode = trex.readElement('tfState');
        objJsonData.cityCode = trex.readElement('tfCity');
        objJsonData.regionCode = trex.readElement('tfRegion');

        var objJsonRequest = new Object();
        objJsonRequest.apiController = 'apiRegion';
        objJsonRequest.apiMethod = 'validateRegion';
        objJsonRequest.apiData = JSON.stringify(objJsonData);

        trex.doDataBridge(objJsonRequest,
            functionSuccess,
            null,
            functionFailure,
            null);
    },

    onButtonClick: function (button, e, eOpts) {
        trex.showWindow('winRegionSearch');
        trex.refreshGrid('gridRegion');
    }

});