/*
 * File: app/view/winCustomer.js
 *
 * This file was generated by Sencha Architect version 3.5.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('catCustomer.view.winCustomer', {
    extend: 'Ext.window.Window',
    alias: 'widget.winCustomer',

    requires: [
        'catCustomer.view.winCustomerViewModel',
        'Ext.form.Panel',
        'Ext.form.FieldSet',
        'Ext.form.field.Date',
        'Ext.form.field.Checkbox',
        'Ext.toolbar.Toolbar',
        'Ext.button.Button',
        'Ext.toolbar.Fill'
    ],

    viewModel: {
        type: 'wincustomer'
    },
    height: 530,
    id: 'winCustomer',
    itemId: 'winCustomer',
    minHeight: 500,
    minWidth: 850,
    ui: 'green-window',
    width: 850,
    layout: 'column',
    closable: false,
    title: 'Customer',
    modal: true,

    items: [
        {
            xtype: 'form',
            confirmRecord: function() {
                if(Ext.getCmp('formCustomer').isValid()){
                    var formRecord    = 'formCustomer';
                    var apiController = 'apiCustomer';
                    var apiMethod     = 'createCustomer';

                    var objJsonRequest = new Object();
                    objJsonRequest.apiController = apiController;
                    objJsonRequest.apiMethod     = apiMethod;
                    objJsonRequest.apiData       = trex.prepareFormFields(formRecord);

                    var functionSuccess = function(){
                        var jsonData = trex.getInfoDataBridge(apiController);

                        trex.showInfo(jsonData, 'information');

                        var winCustomer = Ext.getCmp('winCustomer');
                        winCustomer.close();

                        Ext.getStore('storeCustomer').load();

                    };

                    var functionFailure = function(){
                        var jsonData = trex.getInfoDataBridge(apiController);
                        trex.showInfo(jsonData, 'error', 'tfCompany');
                    };

                    trex.doDataBridge(objJsonRequest,
                    functionSuccess,
                    null,
                    functionFailure,
                    null);

                }
                else{

                    trex.message('error',
                    'Incomplete Form',
                    'You must fill the required fields');
                }
            },
            columnWidth: 1,
            id: 'formCustomer',
            itemId: 'formCustomer',
            layout: 'column',
            bodyPadding: 10,
            items: [
                {
                    xtype: 'fieldset',
                    columnWidth: 1,
                    id: 'fieldsetCustomerInformation',
                    itemId: 'fieldsetCustomerInformation',
                    layout: 'column',
                    title: '<b>General information</b>',
                    items: [
                        {
                            xtype: 'textfield',
                            columnWidth: 0.6,
                            disabledCls: 'disabledField',
                            id: 'tfCompany',
                            itemId: 'tfCompany',
                            margin: '0 5 5 5',
                            fieldLabel: 'Company',
                            labelClsExtra: 'requiredField',
                            allowBlank: false
                        },
                        {
                            xtype: 'textfield',
                            columnWidth: 0.4,
                            disabledCls: 'disabledField',
                            id: 'tfTaxId',
                            itemId: 'tfTaxId',
                            margin: '0 5 5 5',
                            fieldLabel: 'Tax ID',
                            labelClsExtra: 'requiredField',
                            allowBlank: false
                        },
                        {
                            xtype: 'textfield',
                            columnWidth: 0.4,
                            disabledCls: 'disabledField',
                            id: 'tfShortName',
                            itemId: 'tfShortName',
                            margin: '0 5 5 5',
                            fieldLabel: 'Short Name',
                            labelClsExtra: 'requiredField',
                            allowBlank: false
                        },
                        {
                            xtype: 'textfield',
                            columnWidth: 0.4,
                            disabledCls: 'disabledField',
                            id: 'tfPassword',
                            itemId: 'tfPassword',
                            margin: '0 5 5 5',
                            fieldLabel: 'Password',
                            inputType: 'password'
                        },
                        {
                            xtype: 'datefield',
                            columnWidth: 0.3,
                            disabledCls: 'disabledField',
                            id: 'dtCreatedAt',
                            itemId: 'dtCreatedAt',
                            margin: '0 5 5 5',
                            fieldLabel: 'Created'
                        },
                        {
                            xtype: 'checkboxfield',
                            columnWidth: 0.5,
                            disabledCls: 'disabledField',
                            id: 'chActive',
                            itemId: 'chActive',
                            margin: '0 5 5 5',
                            boxLabel: 'Active'
                        }
                    ]
                },
                {
                    xtype: 'fieldset',
                    columnWidth: 1,
                    id: 'fieldsetAddress',
                    itemId: 'fieldsetAddress',
                    layout: 'column',
                    title: '<b>Address</b>',
                    items: [
                        {
                            xtype: 'textfield',
                            columnWidth: 1,
                            disabledCls: 'disabledField',
                            id: 'tfAddress',
                            itemId: 'tfAddress',
                            margin: '0 5 5 5',
                            fieldLabel: 'Address',
                            labelClsExtra: 'requiredField',
                            allowBlank: false
                        },
                        {
                            xtype: 'textfield',
                            columnWidth: 0.33,
                            disabledCls: 'disabledField',
                            id: 'tfZipCode',
                            itemId: 'tfZipCode',
                            margin: '0 5 5 5',
                            fieldLabel: 'Zip Code',
                            labelClsExtra: 'requiredField',
                            allowBlank: false
                        },
                        {
                            xtype: 'textfield',
                            columnWidth: 0.33,
                            disabledCls: 'disabledField',
                            id: 'tfLocation',
                            itemId: 'tfLocation',
                            margin: '0 5 5 5',
                            fieldLabel: 'Location',
                            labelClsExtra: 'requiredField',
                            allowBlank: false
                        },
                        {
                            xtype: 'textfield',
                            columnWidth: 0.33,
                            disabledCls: 'disabledField',
                            id: 'tfRegion',
                            itemId: 'tfRegion',
                            margin: '0 5 5 5',
                            fieldLabel: 'Region',
                            labelClsExtra: 'requiredField',
                            allowBlank: false
                        },
                        {
                            xtype: 'textfield',
                            columnWidth: 0.33,
                            disabledCls: 'disabledField',
                            id: 'tfCity',
                            itemId: 'tfCity',
                            margin: '0 5 5 5',
                            fieldLabel: 'City',
                            labelClsExtra: 'requiredField',
                            allowBlank: false
                        },
                        {
                            xtype: 'textfield',
                            columnWidth: 0.33,
                            disabledCls: 'disabledField',
                            id: 'tfCountry',
                            itemId: 'tfCountry',
                            margin: '0 5 5 5',
                            fieldLabel: 'Country',
                            labelClsExtra: 'requiredField',
                            allowBlank: false
                        }
                    ]
                },
                {
                    xtype: 'fieldset',
                    columnWidth: 1,
                    id: 'fieldsetContact',
                    itemId: 'fieldsetContact',
                    layout: 'column',
                    title: '<b>Contact</b>',
                    items: [
                        {
                            xtype: 'textfield',
                            columnWidth: 0.5,
                            disabledCls: 'disabledField',
                            id: 'tfContactName',
                            itemId: 'tfContactName',
                            margin: '0 5 5 5',
                            fieldLabel: 'Contact Name',
                            labelClsExtra: 'requiredField',
                            allowBlank: false
                        },
                        {
                            xtype: 'textfield',
                            columnWidth: 0.5,
                            disabledCls: 'disabledField',
                            id: 'tfContactPhone',
                            itemId: 'tfContactPhone',
                            margin: '0 5 5 5',
                            fieldLabel: 'Contact Phone',
                            labelClsExtra: 'requiredField',
                            allowBlank: false
                        },
                        {
                            xtype: 'textfield',
                            columnWidth: 0.5,
                            disabledCls: 'disabledField',
                            id: 'tfEmail',
                            itemId: 'tfEmail',
                            margin: '0 5 5 5',
                            fieldLabel: 'Email',
                            labelClsExtra: 'requiredField',
                            allowBlank: false
                        },
                        {
                            xtype: 'textfield',
                            columnWidth: 0.5,
                            disabledCls: 'disabledField',
                            id: 'tfPhone',
                            itemId: 'tfPhone',
                            margin: '0 5 5 5',
                            fieldLabel: 'Phone'
                        },
                        {
                            xtype: 'textfield',
                            columnWidth: 0.5,
                            disabledCls: 'disabledField',
                            id: 'tfWebsite',
                            itemId: 'tfWebsite',
                            margin: '0 5 5 5',
                            fieldLabel: 'tfWebsite'
                        }
                    ]
                },
                {
                    xtype: 'fieldset',
                    columnWidth: 1,
                    id: 'fieldsetGeolocalization',
                    itemId: 'fieldsetGeolocalization',
                    layout: 'column',
                    title: '<b>Geolocalization</b>',
                    items: [
                        {
                            xtype: 'textfield',
                            columnWidth: 0.5,
                            disabledCls: 'disabledField',
                            id: 'tfLatitude',
                            itemId: 'tfLatitude',
                            margin: '0 5 5 5',
                            fieldLabel: 'Latitude',
                            labelClsExtra: ''
                        },
                        {
                            xtype: 'textfield',
                            columnWidth: 0.5,
                            disabledCls: 'disabledField',
                            id: 'tfLongitude',
                            itemId: 'tfLongitude',
                            margin: '0 5 5 5',
                            fieldLabel: 'Longitude',
                            labelClsExtra: ''
                        },
                        {
                            xtype: 'textfield',
                            columnWidth: 1,
                            disabledCls: 'disabledField',
                            id: 'tfGeocodeUrl',
                            itemId: 'tfGeocodeUrl',
                            margin: '0 5 5 5',
                            fieldLabel: 'Geocode URL'
                        }
                    ]
                }
            ]
        }
    ],
    dockedItems: [
        {
            xtype: 'toolbar',
            dock: 'top',
            id: 'toolbarCustomer',
            itemId: 'toolbarCustomer',
            items: [
                {
                    xtype: 'button',
                    handler: function(button, e) {
                        Ext.getCmp('formCustomer').confirmRecord();
                    },
                    id: 'btnConfirmCustomer',
                    itemId: 'btnConfirmCustomer',
                    width: 120,
                    iconCls: 'ion-checkmark-circled icon16',
                    text: 'Confirm',
                    textAlign: 'left'
                },
                {
                    xtype: 'tbfill',
                    id: 'filCustomer',
                    itemId: 'filCustomer'
                },
                {
                    xtype: 'button',
                    handler: function(button, e) {
                        var winCustomer = Ext.getCmp('winCustomer');
                        winCustomer.close();
                    },
                    id: 'btnCloseCustomer',
                    itemId: 'btnCloseCustomer',
                    width: 120,
                    iconCls: 'ion-close-circled icon16',
                    text: 'Close',
                    textAlign: 'left'
                }
            ]
        }
    ]

});