/*
 * File: app/model/modPayments.js
 *
 * This file was generated by Sencha Architect version 3.5.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('proPayments.model.modPayments', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.field.Field'
    ],

    fields: [
        {
            name: 'pay_cust_id'
        },
        {
            name: 'pay_document'
        },
        {
            name: 'pay_date'
        },
        {
            name: 'pay_period'
        },
        {
            name: 'pay_amount'
        },
        {
            name: 'pay_tax'
        },
        {
            name: 'pay_total'
        },
        {
            name: 'pay_status'
        }
    ]
});