/*
 * File: app/model/modSerDetail.js
 *
 * This file was generated by Sencha Architect version 3.5.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('proPayments.model.modSerDetail', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.field.Field'
    ],

    fields: [
        {
            name: 'service_id'
        },
        {
            name: 'num_service'
        },
        {
            name: 'service_date'
        },
        {
            name: 'period'
        },
        {
            name: 'customer_id'
        },
        {
            name: 'branch_office'
        },
        {
            name: 'authorizer'
        },
        {
            name: 'sector'
        },
        {
            name: 'zone_end'
        },
        {
            name: 'depart_time'
        },
        {
            name: 'appointment'
        },
        {
            name: 'appointment_date'
        },
        {
            name: 'range'
        },
        {
            name: 'time'
        },
        {
            name: 'time_wait'
        },
        {
            name: 'add_cost'
        },
        {
            name: 'taxt'
        },
        {
            name: 'cost'
        },
        {
            name: 'status'
        },
        {
            name: 'total'
        }
    ]
});