/*
 * File: app/view/winExpenses.js
 *
 * This file was generated by Sencha Architect version 3.5.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('proPayments.view.winExpenses', {
    extend: 'Ext.window.Window',
    alias: 'widget.winExpenses',

    requires: [
        'proPayments.view.winExpensesViewModel',
        'Ext.form.Panel',
        'Ext.form.FieldSet',
        'Ext.form.field.Date',
        'Ext.form.field.TextArea',
        'Ext.form.field.Checkbox',
        'Ext.toolbar.Toolbar',
        'Ext.button.Button',
        'Ext.toolbar.Fill'
    ],

    viewModel: {
        type: 'winexpenses'
    },
    height: 250,
    id: 'winExpenses',
    itemId: 'winExpenses',
    maxHeight: 350,
    minHeight: 500,
    minWidth: 850,
    ui: 'green-window',
    width: 850,
    layout: 'column',
    closable: false,
    title: 'Expenses',
    modal: true,

    items: [
        {
            xtype: 'form',
            confirmRecord: function () {
                if (Ext.getCmp('formExpenses').isValid()) {
                    var formRecord = 'formExpenses';
                    var apiController = 'apiExpenses';
                    var apiMethod = 'createExpenses';

                    var objJsonRequest = new Object();
                    objJsonRequest.apiController = apiController;
                    objJsonRequest.apiMethod = apiMethod;
                    objJsonRequest.apiData = trex.prepareFormFields(formRecord);

                    var functionSuccess = function () {
                        var jsonData = trex.getInfoDataBridge(apiController);

                        trex.showInfo(jsonData, 'information');

                        var winExpenses = Ext.getCmp('winExpenses');
                        winExpenses.close();

                        Ext.getStore('storeExpenses').load();

                    };

                    var functionFailure = function () {
                        var jsonData = trex.getInfoDataBridge(apiController);
                        trex.showInfo(jsonData, 'error', 'tfNum_Service');
                    };

                    trex.doDataBridge(objJsonRequest,
                        functionSuccess,
                        null,
                        functionFailure,
                        null);

                }
                else {

                    trex.message('error',
                        'Incomplete Form',
                        'You must fill the required fields');
                }
            },
            columnWidth: 1,
            height: 279,
            id: 'formExpenses',
            itemId: 'formExpenses',
            width: 838,
            layout: 'column',
            bodyPadding: 10,
            items: [
                {
                    xtype: 'fieldset',
                    columnWidth: 1,
                    height: 227,
                    id: 'fieldsetExpensesInformation',
                    itemId: 'fieldsetExpensesInformation',
                    width: 816,
                    layout: 'column',
                    title: '<b>General information</b>',
                    items: [
                        {
                            xtype: 'textfield',
                            columnWidth: 0.27,
                            disabledCls: 'disabledField',
                            id: 'tfNumService',
                            itemId: 'tfNumService',
                            margin: '0 5 5 5',
                            fieldLabel: 'Num.Service',
                            labelClsExtra: 'requiredField',
                            labelWidth: 110,
                            allowBlank: false
                        },
                        {
                            xtype: 'textfield',
                            columnWidth: 0.73,
                            disabledCls: 'disabledField',
                            id: 'tfSpendDesc',
                            itemId: 'tfSpendDesc',
                            margin: '0 5 5 10',
                            fieldLabel: 'Expense Descip',
                            labelClsExtra: 'requiredField',
                            labelWidth: 120,
                            allowBlank: false
                        },
                        {
                            xtype: 'datefield',
                            columnWidth: 0.3,
                            disabledCls: 'disabledField',
                            id: 'dtSpendDate',
                            itemId: 'dtSpendDate',
                            margin: '0 5 5 5',
                            fieldLabel: 'Date Spending',
                            labelClsExtra: 'requiredField',
                            labelWidth: 110,
                            allowBlank: false
                        },
                        {
                            xtype: 'textfield',
                            columnWidth: 0.33,
                            disabledCls: 'disabledField',
                            id: 'tfInvoiceTicket',
                            itemId: 'tfInvoiceTicket',
                            margin: '0 5 5 5',
                            fieldLabel: 'Invoice/Ticket',
                            labelClsExtra: 'requiredField',
                            allowBlank: false
                        },
                        {
                            xtype: 'textfield',
                            columnWidth: 0.35,
                            disabledCls: 'disabledField',
                            id: 'tfAmount',
                            itemId: 'tfAmount',
                            margin: '0 5 5 5',
                            width: 80,
                            fieldLabel: 'Amount',
                            labelClsExtra: 'requiredField',
                            labelWidth: 80,
                            allowBlank: false
                        },
                        {
                            xtype: 'textfield',
                            columnWidth: 0.98,
                            disabledCls: 'disabledField',
                            id: 'tfTax',
                            itemId: 'tfTax',
                            margin: '0 5 5 505',
                            fieldLabel: 'Tax',
                            labelWidth: 80,
                            allowBlank: false
                        },
                        {
                            xtype: 'textfield',
                            columnWidth: 0.98,
                            disabledCls: 'disabledField',
                            id: 'tfTotal',
                            itemId: 'tfTotal',
                            margin: '0 5 5 505',
                            fieldLabel: 'Total',
                            labelClsExtra: 'requiredField',
                            labelWidth: 80,
                            allowBlank: false
                        },
                        {
                            xtype: 'textareafield',
                            columnWidth: 1,
                            disabledCls: 'disabledField',
                            id: 'tfNote',
                            itemId: 'tfNote',
                            margin: '0 5 5 5',
                            fieldLabel: 'Note',
                            labelClsExtra: 'requiredField',
                            labelWidth: 110,
                            allowBlank: false
                        },
                        {
                            xtype: 'checkboxfield',
                            columnWidth: 0.17,
                            disabledCls: 'disabledField',
                            id: 'chApproved',
                            itemId: 'chApproved',
                            margin: '0 5 5 5',
                            labelClsExtra: 'requiredField',
                            boxLabel: 'Approved'
                        }
                    ]
                }
            ]
        }
    ],
    dockedItems: [
        {
            xtype: 'toolbar',
            dock: 'top',
            id: 'toolbarExpenses',
            itemId: 'toolbarExpenses',
            items: [
                {
                    xtype: 'button',
                    handler: function (button, e) {
                        Ext.getCmp('formExpenses').confirmRecord();
                    },
                    id: 'btnConfirmExpenses',
                    itemId: 'btnConfirmExpenses',
                    width: 120,
                    iconCls: 'ion-checkmark-circled icon16',
                    text: 'Confirm',
                    textAlign: 'left'
                },
                {
                    xtype: 'tbfill',
                    id: 'filExpenses',
                    itemId: 'filExpenses'
                },
                {
                    xtype: 'button',
                    handler: function (button, e) {
                        var winExpenses = Ext.getCmp('winExpenses');
                        winExpenses.close();
                    },
                    id: 'btnCloseExpenses',
                    itemId: 'btnCloseExpenses',
                    width: 120,
                    iconCls: 'ion-close-circled icon16',
                    text: 'Close',
                    textAlign: 'left'
                }
            ]
        }
    ]

});