/*
 * File: app/view/formMaintenance.js
 *
 * This file was generated by Sencha Architect version 3.5.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('catSector.view.formMaintenance', {
    extend: 'Ext.form.Panel',
    alias: 'widget.formMaintenance',

    requires: [
        'catSector.view.formMaintenanceViewModel',
        'Ext.button.Button',
        'Ext.toolbar.Separator',
        'Ext.toolbar.Fill',
        'Ext.grid.Panel',
        'Ext.view.Table',
        'Ext.grid.column.Column',
        'Ext.toolbar.Paging'
    ],

    viewModel: {
        type: 'formmaintenance'
    },
    id: 'formMaintenance',
    itemId: 'formMaintenance',
    ui: 'green-panel',
    layout: 'column',
    bodyPadding: 10,
    manageHeight: false,
    defaultListenerScope: true,

    dockedItems: [
        {
            xtype: 'toolbar',
            dock: 'top',
            id: 'toolbarMaintenance',
            itemId: 'toolbarMaintenance',
            items: [
                {
                    xtype: 'button',
                    handler: function (button, e) {
                        Ext.getCmp('formMaintenance').showSector();
                    },
                    id: 'btnView',
                    itemId: 'btnView',
                    width: 120,
                    iconCls: 'ion-eye icon16',
                    text: 'View',
                    textAlign: 'left'
                },
                {
                    xtype: 'button',
                    handler: function (button, e) {
                        var winSector = Ext.getCmp('winSector');

                        if (!winSector) {
                            winSector = Ext.create('widget.winSector');
                            winSector.show();
                            trex.hideScrollBars();
                        }
                    },
                    id: 'btnCreate',
                    itemId: 'btnCreate',
                    width: 120,
                    iconCls: 'ion-plus-circled icon16',
                    text: 'Create',
                    textAlign: 'left'
                },
                {
                    xtype: 'button',
                    handler: function (button, e) {
                        Ext.getCmp('formMaintenance').showSector('edit');
                    },
                    id: 'btnUpdate',
                    itemId: 'btnUpdate',
                    width: 120,
                    iconCls: 'ion-edit icon16',
                    text: 'Update',
                    textAlign: 'left'
                },
                {
                    xtype: 'button',
                    handler: function (button, e) {
                        var msgFunction = function () {
                            Ext.getCmp('formMaintenance').deleteSector();

                        };

                        var msgType = 'question';
                        var msgTitle = 'Delete Sector';
                        var msgContent = 'Do you want to delete the Sector record: ';

                        trex.message(msgType,
                            msgTitle,
                            msgContent,
                            msgFunction);

                        return;
                    },
                    id: 'btnDelete',
                    itemId: 'btnDelete',
                    width: 120,
                    iconCls: 'ion-trash-a icon16',
                    text: 'Delete',
                    textAlign: 'left'
                },
                {
                    xtype: 'tbseparator',
                    width: 30
                },
                {
                    xtype: 'button',
                    id: 'btnFind',
                    itemId: 'btnFind',
                    width: 120,
                    iconCls: 'ion-ios-search-strong icon16',
                    text: 'Find',
                    textAlign: 'left'
                },
                {
                    xtype: 'button',
                    id: 'btnFilter',
                    itemId: 'btnFilter',
                    width: 120,
                    iconCls: 'ion-funnel icon16',
                    text: 'Filter',
                    textAlign: 'left'
                },
                {
                    xtype: 'tbseparator',
                    width: 30
                },
                {
                    xtype: 'tbfill'
                },
                {
                    xtype: 'button',
                    id: 'btnInformation',
                    itemId: 'btnInformation',
                    width: 120,
                    iconCls: 'ion-information-circled icon16',
                    text: 'Information',
                    textAlign: 'left'
                },
                {
                    xtype: 'button',
                    handler: function (button, e) {
                        var win = window.parent.Ext.getCmp('catSector');
                        if (win)win[win.closeAction]();
                    },
                    id: 'btnExit',
                    itemId: 'btnExit',
                    width: 120,
                    iconCls: 'ion-android-exit icon16',
                    text: 'Exit',
                    textAlign: 'left'
                }
            ]
        }
    ],
    items: [
        {
            xtype: 'gridpanel',
            columnWidth: 0.6,
            height: 400,
            id: 'gridSector',
            itemId: 'gridSector',
            ui: 'green-panel',
            width: 800,
            title: 'Sector',
            columnLines: false,
            forceFit: true,
            store: 'storeSector',
            columns: [
                {
                    xtype: 'gridcolumn',
                    id: 'sector_id',
                    itemId: 'sector_id',
                    dataIndex: 'sector_id',
                    text: 'SectorID'
                },
                {
                    xtype: 'gridcolumn',
                    id: 'sector_name',
                    itemId: 'sector_name',
                    maxWidth: 300,
                    width: 300,
                    dataIndex: 'sector_name',
                    text: 'Sector Name'
                },
                {
                    xtype: 'gridcolumn',
                    id: 'sector_state',
                    itemId: 'sector_state',
                    maxWidth: 120,
                    width: 120,
                    dataIndex: 'sector_state',
                    text: 'State'
                },
                {
                    xtype: 'gridcolumn',
                    id: 'sector_country',
                    itemId: 'sector_country',
                    dataIndex: 'sector_country',
                    text: 'Country'
                },
                {
                    xtype: 'gridcolumn',
                    id: 'created_date',
                    itemId: 'created_date',
                    dataIndex: 'created_at',
                    text: 'Fecha </br> Registro'
                },
                {
                    xtype: 'gridcolumn',
                    id: 'isactive',
                    itemId: 'isactive',
                    maxWidth: 50,
                    minWidth: 30,
                    dataIndex: 'is_active',
                    text: 'Active'
                }
            ],
            dockedItems: [
                {
                    xtype: 'pagingtoolbar',
                    dock: 'bottom',
                    id: 'pagingToolbar',
                    itemId: 'pagingToolbar',
                    width: 260,
                    displayInfo: true,
                    store: 'storeSector',
                    items: [
                        {
                            xtype: 'tbseparator',
                            width: 30
                        },
                        {
                            xtype: 'button',
                            handler: function (button, e) {
                                var winSector = Ext.getCmp('winSector');

                                if (!winSector) {
                                    winSector = Ext.create('widget.winSector');
                                    winSector.show();
                                    trex.hideScrollBars();
                                }
                            },
                            id: 'btnAddSector',
                            itemId: 'btnAddSector',
                            width: 100,
                            iconCls: 'ion-android-add-circle icon16',
                            text: 'Add',
                            textAlign: 'left'
                        },
                        {
                            xtype: 'button',
                            handler: function (button, e) {

                            },
                            id: 'btnUpdateSector',
                            itemId: 'btnUpdateSector',
                            width: 100,
                            iconCls: 'ion-ios-compose icon16',
                            text: 'Update',
                            textAlign: 'left'
                        },
                        {
                            xtype: 'button',
                            handler: function (button, e) {

                            },
                            id: 'btnDeleteSector',
                            itemId: 'btnDeleteSector',
                            width: 100,
                            iconCls: 'ion-android-delete icon16',
                            text: 'Update',
                            textAlign: 'left'
                        }
                    ]
                }
            ],
            listeners: {
                itemdblclick: 'onGridSectorItemDblClick',
                itemclick: 'onGridSectorItemClick'
            }
        },
        {
            xtype: 'gridpanel',
            columnWidth: 0.4,
            height: 400,
            id: 'gridZone',
            itemId: 'gridZone',
            margin: '0 0 0 15',
            ui: 'green-panel',
            width: 400,
            title: 'Zone',
            columnLines: false,
            forceFit: true,
            store: 'storeZone',
            viewConfig: {
                height: 400
            },
            columns: [
                {
                    xtype: 'gridcolumn',
                    id: 'zone_id',
                    itemId: 'zone_id',
                    maxWidth: 100,
                    dataIndex: 'zone_id',
                    text: 'ZonaID'
                },
                {
                    xtype: 'gridcolumn',
                    id: 'zone_name',
                    itemId: 'zone_name',
                    dataIndex: 'zone_name',
                    text: 'Zone </br> Name'
                }
            ],
            dockedItems: [
                {
                    xtype: 'pagingtoolbar',
                    dock: 'bottom',
                    id: 'pagingToolbar2',
                    itemId: 'pagingToolbar',
                    width: 260,
                    displayInfo: true,
                    store: 'storeZone'
                }
            ],
            listeners: {
                itemdblclick: 'onGridZoneItemDblClick',
                itemclick: 'onGridZoneItemClick'
            }
        }
    ],

    onGridSectorItemDblClick: function (dataview, record, item, index, e, eOpts) {
        Ext.getCmp('formMaintenance').showSector();
    },

    onGridSectorItemClick: function (dataview, record, item, index, e, eOpts) {
        Ext.getCmp('formMaintenance').SectorID = record.data.id;
        Ext.getCmp('formMaintenance').SectorRecord = record.data;
    },

    onGridZoneItemDblClick: function (dataview, record, item, index, e, eOpts) {
        Ext.getCmp('formMaintenance').showSector();
    },

    onGridZoneItemClick: function (dataview, record, item, index, e, eOpts) {
        Ext.getCmp('formMaintenance').SectorID = record.data.id;
        Ext.getCmp('formMaintenance').SectorRecord = record.data;
    },

    showSector: function (pMode) {
        var apiController = 'apiSector';
        var apiMethod = 'showSector';
        var objJsonData = new Object();
        objJsonData.SectorID = Ext.getCmp('formMaintenance').SectorID;

        var objJsonRequest = new Object();
        objJsonRequest.apiController = apiController;
        objJsonRequest.apiMethod = apiMethod;
        objJsonRequest.apiData = JSON.stringify(objJsonData);

        var functionSuccess = function () {
            var jsonData = trex.getInfoDataBridge(apiController);


            var winSector = Ext.getCmp('winSector');

            if (!winSector) {
                winSector = Ext.create('widget.winSector');
                winSector.show();
                trex.hideScrollBars();
            }

            trex.showRecord(jsonData, 'sector');

        };

        var functionFailure = function () {
            var jsonData = trex.getInfoDataBridge(apiController);
        };

        trex.doDataBridge(objJsonRequest,
            functionSuccess,
            null,
            functionFailure,
            null);


    },

    deleteSector: function () {
        alert('registro borrado');

        var formRecord = 'formSector';
        var apiController = 'apiSector';
        var apiMethod = 'deleteSector';

        var objJsonData = new Object();
        objJsonData.SectorId = Ext.getCmp('formMaintenance').SectorRecord.id;

        var objJsonRequest = new Object();
        objJsonRequest.apiController = apiController;
        objJsonRequest.apiMethod = apiMethod;
        objJsonRequest.apiData = JSON.stringify(objJsonData);

        var functionSuccess = function () {
            var jsonData = trex.getInfoDataBridge(apiController);

            console.log(jsonData);
            trex.showInfo(jsonData, 'info');

        };

        var functionFailure = function () {
            var jsonData = trex.getInfoDataBridge(apiController);
            trex.showInfo(jsonData, 'error', 'tfCompany');
        };

        trex.doDataBridge(objJsonRequest,
            functionSuccess,
            null,
            functionFailure,
            null);
    }

});