/*
 * File: app/view/formWorkplace.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('workplace.view.formWorkplace', {
    extend: 'Ext.form.Panel',
    alias: 'widget.formworkplace',

    requires: [
        'workplace.view.formWorkplaceViewModel',
        'Ext.toolbar.Toolbar',
        'Ext.toolbar.Fill',
        'Ext.form.Panel',
        'Ext.tab.Panel',
        'Ext.tab.Tab'
    ],

    viewModel: {
        type: 'formworkplace'
    },
    id: 'formWorkplace',
    itemId: 'formWorkplace',
    layout: 'fit',
    bodyPadding: 10,
    manageHeight: false,

    dockedItems: [
        {
            xtype: 'toolbar',
            dock: 'top',
            id: 'toolbarWorkplace',
            itemId: 'toolbarWorkplace',
            items: [
                {
                    xtype: 'tbfill',
                    id: 'filWorkplace',
                    itemId: 'filWorkplace'
                },
                {
                    xtype: 'button',
                    handler: function(button, e) {
                        sessionStorage.clear();
                        self.location="../access/index.html";
                    },
                    height: 24,
                    id: 'btnExitWorkspace',
                    itemId: 'btnExitWorkspace',
                    width: 130,
                    iconCls: 'ion-power icon16red',
                    text: 'Exit',
                    textAlign: 'left'
                }
            ]
        }
    ],
    items: [
        {
            xtype: 'form',
            height: 140,
            id: 'formHeader',
            itemId: 'formHeader',
            maxHeight: 140,
            bodyCls: 'imagenAmbienteMenu',
            bodyPadding: 10
        },
        {
            xtype: 'tabpanel',
            id: 'tabPanelWorkplace',
            itemId: 'tabPanelWorkplace',
            maxHeight: 350,
            activeTab: 0,
            items: [
                {
                    xtype: 'panel',
                    id: 'tabTasks',
                    itemId: 'tabTasks',
                    title: 'Tasks',
                    tabConfig: {
                        xtype: 'tab',
                        height: 32,
                        id: 'tabConfigTasks',
                        itemId: 'tabConfigTasks',
                        width: 120,
                        iconCls: 'ion-gear-a icon24',
                        textAlign: 'left'
                    }
                },
                {
                    xtype: 'panel',
                    id: 'tabQueries',
                    itemId: 'tabQueries',
                    title: 'Queries',
                    tabConfig: {
                        xtype: 'tab',
                        height: 32,
                        id: 'tabConfigQueries',
                        itemId: 'tabConfigQueries',
                        width: 120,
                        iconCls: 'ion-ios-paper icon24',
                        textAlign: 'left'
                    }
                },
                {
                    xtype: 'panel',
                    height: 500,
                    id: 'tabReports',
                    itemId: 'tabReports',
                    title: 'Reports',
                    tabConfig: {
                        xtype: 'tab',
                        height: 32,
                        id: 'tabConfigReports',
                        itemId: 'tabConfigReports',
                        width: 120,
                        iconCls: 'ion-printer icon24',
                        textAlign: 'left'
                    }
                },
                {
                    xtype: 'panel',
                    id: 'tabCatalogs',
                    itemId: 'tabCatalogs',
                    layout: 'column',
                    title: 'Catalogs',
                    tabConfig: {
                        xtype: 'tab',
                        height: 32,
                        id: 'tabConfigCatalogs',
                        itemId: 'tabConfigCatalogs',
                        width: 120,
                        iconCls: 'ion-ios-folder icon24',
                        textAlign: 'left'
                    },
                    items: [
                        {
                            xtype: 'button',
                            handler: function(button, e) {
                                trex.showAppWindow('catCustomer','Customer');
                            },
                            columnWidth: 0.2,
                            cls: 'botonZoom',
                            id: 'btn',
                            itemId: 'btn',
                            margin: '10 10 10 10',
                            padding: '10 10 10 10',
                            iconCls: 'ion-person-stalker icon24',
                            text: 'Customer'
                        }
                    ]
                }
            ]
        }
    ]

});