/*
 * File: app/store/storeExpenses.js
 *
 * This file was generated by Sencha Architect version 3.5.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('proPayments.store.storeExpenses', {
    extend: 'Ext.data.Store',

    requires: [
        'proPayments.model.modExpenses',
        'Ext.data.proxy.Rest',
        'Ext.data.reader.Json'
    ],

    constructor: function (cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            storeId: 'storeExpenses',
            model: 'proPayments.model.modExpenses',
            proxy: {
                type: 'rest',
                url: '',
                reader: {
                    type: 'json',
                    rootProperty: 'Expenses',
                    totalProperty: 'numServices.total'
                }
            },
            listeners: {
                beforeload: {
                    fn: me.onStoreBeforeLoad,
                    scope: me
                }
            }
        }, cfg)]);
    },

    onStoreBeforeLoad: function (store, operation, eOpts) {
        var storeExpenses = Ext.getStore('storeExpenses');
        var proxyExpenses = storeExpenses.getProxy();

        var objJsonData = new Object();
        objJsonData.page = storeExpenses.currentPage;
        objJsonData.start = (storeExpenses.currentPage - 1) * storeExpenses.pageSize;
        objJsonData.limit = storeExpenses.pageSize;

        var objJsonRequest = new Object();
        objJsonRequest.apiController = 'apiExpenses';
        objJsonRequest.apiMethod = 'listExpenses';
        objJsonRequest.apiData = JSON.stringify(objJsonData);

        proxyExpenses.api.read = '../../backend/public/dataBridge/' + objJsonRequest.apiController;
        proxyExpenses.extraParams = objJsonRequest;

    }

});